/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListMigrationCredentials200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListMigrationCredentials200Response{}

// ListMigrationCredentials200Response struct for ListMigrationCredentials200Response
type ListMigrationCredentials200Response struct {
	Data []MigrationCredential `json:"data"`
}

type _ListMigrationCredentials200Response ListMigrationCredentials200Response

// NewListMigrationCredentials200Response instantiates a new ListMigrationCredentials200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListMigrationCredentials200Response(data []MigrationCredential) *ListMigrationCredentials200Response {
	this := ListMigrationCredentials200Response{}
	this.Data = data
	return &this
}

// NewListMigrationCredentials200ResponseWithDefaults instantiates a new ListMigrationCredentials200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListMigrationCredentials200ResponseWithDefaults() *ListMigrationCredentials200Response {
	this := ListMigrationCredentials200Response{}
	return &this
}

// GetData returns the Data field value
func (o *ListMigrationCredentials200Response) GetData() []MigrationCredential {
	if o == nil {
		var ret []MigrationCredential
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListMigrationCredentials200Response) GetDataOk() ([]MigrationCredential, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListMigrationCredentials200Response) SetData(v []MigrationCredential) {
	o.Data = v
}

func (o ListMigrationCredentials200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListMigrationCredentials200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ListMigrationCredentials200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListMigrationCredentials200Response := _ListMigrationCredentials200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListMigrationCredentials200Response)

	if err != nil {
		return err
	}

	*o = ListMigrationCredentials200Response(varListMigrationCredentials200Response)

	return err
}

type NullableListMigrationCredentials200Response struct {
	value *ListMigrationCredentials200Response
	isSet bool
}

func (v NullableListMigrationCredentials200Response) Get() *ListMigrationCredentials200Response {
	return v.value
}

func (v *NullableListMigrationCredentials200Response) Set(val *ListMigrationCredentials200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListMigrationCredentials200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListMigrationCredentials200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListMigrationCredentials200Response(val *ListMigrationCredentials200Response) *NullableListMigrationCredentials200Response {
	return &NullableListMigrationCredentials200Response{value: val, isSet: true}
}

func (v NullableListMigrationCredentials200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListMigrationCredentials200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


