/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1MailboxesPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1MailboxesPostRequest{}

// V1MailboxesPostRequest struct for V1MailboxesPostRequest
type V1MailboxesPostRequest struct {
	Email string `json:"email"`
	// Optional; lockally generates if absent.
	Password *string `json:"password,omitempty"`
	// 5 GB default.
	QuotaBytes *int64 `json:"quota_bytes,omitempty"`
}

type _V1MailboxesPostRequest V1MailboxesPostRequest

// NewV1MailboxesPostRequest instantiates a new V1MailboxesPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1MailboxesPostRequest(email string) *V1MailboxesPostRequest {
	this := V1MailboxesPostRequest{}
	this.Email = email
	var quotaBytes int64 = 5368709120
	this.QuotaBytes = &quotaBytes
	return &this
}

// NewV1MailboxesPostRequestWithDefaults instantiates a new V1MailboxesPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1MailboxesPostRequestWithDefaults() *V1MailboxesPostRequest {
	this := V1MailboxesPostRequest{}
	var quotaBytes int64 = 5368709120
	this.QuotaBytes = &quotaBytes
	return &this
}

// GetEmail returns the Email field value
func (o *V1MailboxesPostRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *V1MailboxesPostRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *V1MailboxesPostRequest) SetEmail(v string) {
	o.Email = v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *V1MailboxesPostRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1MailboxesPostRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *V1MailboxesPostRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *V1MailboxesPostRequest) SetPassword(v string) {
	o.Password = &v
}

// GetQuotaBytes returns the QuotaBytes field value if set, zero value otherwise.
func (o *V1MailboxesPostRequest) GetQuotaBytes() int64 {
	if o == nil || IsNil(o.QuotaBytes) {
		var ret int64
		return ret
	}
	return *o.QuotaBytes
}

// GetQuotaBytesOk returns a tuple with the QuotaBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1MailboxesPostRequest) GetQuotaBytesOk() (*int64, bool) {
	if o == nil || IsNil(o.QuotaBytes) {
		return nil, false
	}
	return o.QuotaBytes, true
}

// HasQuotaBytes returns a boolean if a field has been set.
func (o *V1MailboxesPostRequest) HasQuotaBytes() bool {
	if o != nil && !IsNil(o.QuotaBytes) {
		return true
	}

	return false
}

// SetQuotaBytes gets a reference to the given int64 and assigns it to the QuotaBytes field.
func (o *V1MailboxesPostRequest) SetQuotaBytes(v int64) {
	o.QuotaBytes = &v
}

func (o V1MailboxesPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1MailboxesPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.QuotaBytes) {
		toSerialize["quota_bytes"] = o.QuotaBytes
	}
	return toSerialize, nil
}

func (o *V1MailboxesPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1MailboxesPostRequest := _V1MailboxesPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1MailboxesPostRequest)

	if err != nil {
		return err
	}

	*o = V1MailboxesPostRequest(varV1MailboxesPostRequest)

	return err
}

type NullableV1MailboxesPostRequest struct {
	value *V1MailboxesPostRequest
	isSet bool
}

func (v NullableV1MailboxesPostRequest) Get() *V1MailboxesPostRequest {
	return v.value
}

func (v *NullableV1MailboxesPostRequest) Set(val *V1MailboxesPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1MailboxesPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1MailboxesPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1MailboxesPostRequest(val *V1MailboxesPostRequest) *NullableV1MailboxesPostRequest {
	return &NullableV1MailboxesPostRequest{value: val, isSet: true}
}

func (v NullableV1MailboxesPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1MailboxesPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


