/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ActivateAddOn200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActivateAddOn200Response{}

// ActivateAddOn200Response struct for ActivateAddOn200Response
type ActivateAddOn200Response struct {
	Id string `json:"id"`
	AddOn string `json:"add_on"`
	Status string `json:"status"`
	Message string `json:"message"`
}

type _ActivateAddOn200Response ActivateAddOn200Response

// NewActivateAddOn200Response instantiates a new ActivateAddOn200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActivateAddOn200Response(id string, addOn string, status string, message string) *ActivateAddOn200Response {
	this := ActivateAddOn200Response{}
	this.Id = id
	this.AddOn = addOn
	this.Status = status
	this.Message = message
	return &this
}

// NewActivateAddOn200ResponseWithDefaults instantiates a new ActivateAddOn200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActivateAddOn200ResponseWithDefaults() *ActivateAddOn200Response {
	this := ActivateAddOn200Response{}
	return &this
}

// GetId returns the Id field value
func (o *ActivateAddOn200Response) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ActivateAddOn200Response) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ActivateAddOn200Response) SetId(v string) {
	o.Id = v
}

// GetAddOn returns the AddOn field value
func (o *ActivateAddOn200Response) GetAddOn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AddOn
}

// GetAddOnOk returns a tuple with the AddOn field value
// and a boolean to check if the value has been set.
func (o *ActivateAddOn200Response) GetAddOnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AddOn, true
}

// SetAddOn sets field value
func (o *ActivateAddOn200Response) SetAddOn(v string) {
	o.AddOn = v
}

// GetStatus returns the Status field value
func (o *ActivateAddOn200Response) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ActivateAddOn200Response) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ActivateAddOn200Response) SetStatus(v string) {
	o.Status = v
}

// GetMessage returns the Message field value
func (o *ActivateAddOn200Response) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *ActivateAddOn200Response) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *ActivateAddOn200Response) SetMessage(v string) {
	o.Message = v
}

func (o ActivateAddOn200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActivateAddOn200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["add_on"] = o.AddOn
	toSerialize["status"] = o.Status
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *ActivateAddOn200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"add_on",
		"status",
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActivateAddOn200Response := _ActivateAddOn200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varActivateAddOn200Response)

	if err != nil {
		return err
	}

	*o = ActivateAddOn200Response(varActivateAddOn200Response)

	return err
}

type NullableActivateAddOn200Response struct {
	value *ActivateAddOn200Response
	isSet bool
}

func (v NullableActivateAddOn200Response) Get() *ActivateAddOn200Response {
	return v.value
}

func (v *NullableActivateAddOn200Response) Set(val *ActivateAddOn200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableActivateAddOn200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableActivateAddOn200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActivateAddOn200Response(val *ActivateAddOn200Response) *NullableActivateAddOn200Response {
	return &NullableActivateAddOn200Response{value: val, isSet: true}
}

func (v NullableActivateAddOn200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActivateAddOn200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


