/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Mailbox type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Mailbox{}

// Mailbox struct for Mailbox
type Mailbox struct {
	Id string `json:"id"`
	TenantId string `json:"tenant_id"`
	DomainId string `json:"domain_id"`
	Email string `json:"email"`
	QuotaBytes int64 `json:"quota_bytes"`
	Disabled bool `json:"disabled"`
	DisabledAt *time.Time `json:"disabled_at,omitempty"`
	SoftDeletedAt *time.Time `json:"soft_deleted_at,omitempty"`
	HardDeleteAfter *time.Time `json:"hard_delete_after,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	// ONLY present on POST response when lockally generated the password. Shown once.
	Password *string `json:"password,omitempty"`
}

type _Mailbox Mailbox

// NewMailbox instantiates a new Mailbox object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailbox(id string, tenantId string, domainId string, email string, quotaBytes int64, disabled bool, createdAt time.Time) *Mailbox {
	this := Mailbox{}
	this.Id = id
	this.TenantId = tenantId
	this.DomainId = domainId
	this.Email = email
	this.QuotaBytes = quotaBytes
	this.Disabled = disabled
	this.CreatedAt = createdAt
	return &this
}

// NewMailboxWithDefaults instantiates a new Mailbox object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailboxWithDefaults() *Mailbox {
	this := Mailbox{}
	return &this
}

// GetId returns the Id field value
func (o *Mailbox) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Mailbox) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Mailbox) SetId(v string) {
	o.Id = v
}

// GetTenantId returns the TenantId field value
func (o *Mailbox) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *Mailbox) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *Mailbox) SetTenantId(v string) {
	o.TenantId = v
}

// GetDomainId returns the DomainId field value
func (o *Mailbox) GetDomainId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DomainId
}

// GetDomainIdOk returns a tuple with the DomainId field value
// and a boolean to check if the value has been set.
func (o *Mailbox) GetDomainIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DomainId, true
}

// SetDomainId sets field value
func (o *Mailbox) SetDomainId(v string) {
	o.DomainId = v
}

// GetEmail returns the Email field value
func (o *Mailbox) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *Mailbox) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *Mailbox) SetEmail(v string) {
	o.Email = v
}

// GetQuotaBytes returns the QuotaBytes field value
func (o *Mailbox) GetQuotaBytes() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.QuotaBytes
}

// GetQuotaBytesOk returns a tuple with the QuotaBytes field value
// and a boolean to check if the value has been set.
func (o *Mailbox) GetQuotaBytesOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.QuotaBytes, true
}

// SetQuotaBytes sets field value
func (o *Mailbox) SetQuotaBytes(v int64) {
	o.QuotaBytes = v
}

// GetDisabled returns the Disabled field value
func (o *Mailbox) GetDisabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value
// and a boolean to check if the value has been set.
func (o *Mailbox) GetDisabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Disabled, true
}

// SetDisabled sets field value
func (o *Mailbox) SetDisabled(v bool) {
	o.Disabled = v
}

// GetDisabledAt returns the DisabledAt field value if set, zero value otherwise.
func (o *Mailbox) GetDisabledAt() time.Time {
	if o == nil || IsNil(o.DisabledAt) {
		var ret time.Time
		return ret
	}
	return *o.DisabledAt
}

// GetDisabledAtOk returns a tuple with the DisabledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Mailbox) GetDisabledAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DisabledAt) {
		return nil, false
	}
	return o.DisabledAt, true
}

// HasDisabledAt returns a boolean if a field has been set.
func (o *Mailbox) HasDisabledAt() bool {
	if o != nil && !IsNil(o.DisabledAt) {
		return true
	}

	return false
}

// SetDisabledAt gets a reference to the given time.Time and assigns it to the DisabledAt field.
func (o *Mailbox) SetDisabledAt(v time.Time) {
	o.DisabledAt = &v
}

// GetSoftDeletedAt returns the SoftDeletedAt field value if set, zero value otherwise.
func (o *Mailbox) GetSoftDeletedAt() time.Time {
	if o == nil || IsNil(o.SoftDeletedAt) {
		var ret time.Time
		return ret
	}
	return *o.SoftDeletedAt
}

// GetSoftDeletedAtOk returns a tuple with the SoftDeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Mailbox) GetSoftDeletedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.SoftDeletedAt) {
		return nil, false
	}
	return o.SoftDeletedAt, true
}

// HasSoftDeletedAt returns a boolean if a field has been set.
func (o *Mailbox) HasSoftDeletedAt() bool {
	if o != nil && !IsNil(o.SoftDeletedAt) {
		return true
	}

	return false
}

// SetSoftDeletedAt gets a reference to the given time.Time and assigns it to the SoftDeletedAt field.
func (o *Mailbox) SetSoftDeletedAt(v time.Time) {
	o.SoftDeletedAt = &v
}

// GetHardDeleteAfter returns the HardDeleteAfter field value if set, zero value otherwise.
func (o *Mailbox) GetHardDeleteAfter() time.Time {
	if o == nil || IsNil(o.HardDeleteAfter) {
		var ret time.Time
		return ret
	}
	return *o.HardDeleteAfter
}

// GetHardDeleteAfterOk returns a tuple with the HardDeleteAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Mailbox) GetHardDeleteAfterOk() (*time.Time, bool) {
	if o == nil || IsNil(o.HardDeleteAfter) {
		return nil, false
	}
	return o.HardDeleteAfter, true
}

// HasHardDeleteAfter returns a boolean if a field has been set.
func (o *Mailbox) HasHardDeleteAfter() bool {
	if o != nil && !IsNil(o.HardDeleteAfter) {
		return true
	}

	return false
}

// SetHardDeleteAfter gets a reference to the given time.Time and assigns it to the HardDeleteAfter field.
func (o *Mailbox) SetHardDeleteAfter(v time.Time) {
	o.HardDeleteAfter = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Mailbox) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Mailbox) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Mailbox) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *Mailbox) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Mailbox) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *Mailbox) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *Mailbox) SetPassword(v string) {
	o.Password = &v
}

func (o Mailbox) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Mailbox) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["domain_id"] = o.DomainId
	toSerialize["email"] = o.Email
	toSerialize["quota_bytes"] = o.QuotaBytes
	toSerialize["disabled"] = o.Disabled
	if !IsNil(o.DisabledAt) {
		toSerialize["disabled_at"] = o.DisabledAt
	}
	if !IsNil(o.SoftDeletedAt) {
		toSerialize["soft_deleted_at"] = o.SoftDeletedAt
	}
	if !IsNil(o.HardDeleteAfter) {
		toSerialize["hard_delete_after"] = o.HardDeleteAfter
	}
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	return toSerialize, nil
}

func (o *Mailbox) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"tenant_id",
		"domain_id",
		"email",
		"quota_bytes",
		"disabled",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailbox := _Mailbox{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMailbox)

	if err != nil {
		return err
	}

	*o = Mailbox(varMailbox)

	return err
}

type NullableMailbox struct {
	value *Mailbox
	isSet bool
}

func (v NullableMailbox) Get() *Mailbox {
	return v.value
}

func (v *NullableMailbox) Set(val *Mailbox) {
	v.value = val
	v.isSet = true
}

func (v NullableMailbox) IsSet() bool {
	return v.isSet
}

func (v *NullableMailbox) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailbox(val *Mailbox) *NullableMailbox {
	return &NullableMailbox{value: val, isSet: true}
}

func (v NullableMailbox) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailbox) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


