/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CalendarIntegration type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CalendarIntegration{}

// CalendarIntegration struct for CalendarIntegration
type CalendarIntegration struct {
	Id string `json:"id"`
	TenantId string `json:"tenant_id"`
	Provider string `json:"provider"`
	Label *string `json:"label,omitempty"`
	Status string `json:"status"`
	LastSyncAt *time.Time `json:"last_sync_at,omitempty"`
	ErrorMessage *string `json:"error_message,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type _CalendarIntegration CalendarIntegration

// NewCalendarIntegration instantiates a new CalendarIntegration object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCalendarIntegration(id string, tenantId string, provider string, status string, createdAt time.Time, updatedAt time.Time) *CalendarIntegration {
	this := CalendarIntegration{}
	this.Id = id
	this.TenantId = tenantId
	this.Provider = provider
	this.Status = status
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewCalendarIntegrationWithDefaults instantiates a new CalendarIntegration object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCalendarIntegrationWithDefaults() *CalendarIntegration {
	this := CalendarIntegration{}
	return &this
}

// GetId returns the Id field value
func (o *CalendarIntegration) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CalendarIntegration) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CalendarIntegration) SetId(v string) {
	o.Id = v
}

// GetTenantId returns the TenantId field value
func (o *CalendarIntegration) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *CalendarIntegration) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *CalendarIntegration) SetTenantId(v string) {
	o.TenantId = v
}

// GetProvider returns the Provider field value
func (o *CalendarIntegration) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *CalendarIntegration) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *CalendarIntegration) SetProvider(v string) {
	o.Provider = v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *CalendarIntegration) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarIntegration) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *CalendarIntegration) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *CalendarIntegration) SetLabel(v string) {
	o.Label = &v
}

// GetStatus returns the Status field value
func (o *CalendarIntegration) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CalendarIntegration) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CalendarIntegration) SetStatus(v string) {
	o.Status = v
}

// GetLastSyncAt returns the LastSyncAt field value if set, zero value otherwise.
func (o *CalendarIntegration) GetLastSyncAt() time.Time {
	if o == nil || IsNil(o.LastSyncAt) {
		var ret time.Time
		return ret
	}
	return *o.LastSyncAt
}

// GetLastSyncAtOk returns a tuple with the LastSyncAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarIntegration) GetLastSyncAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastSyncAt) {
		return nil, false
	}
	return o.LastSyncAt, true
}

// HasLastSyncAt returns a boolean if a field has been set.
func (o *CalendarIntegration) HasLastSyncAt() bool {
	if o != nil && !IsNil(o.LastSyncAt) {
		return true
	}

	return false
}

// SetLastSyncAt gets a reference to the given time.Time and assigns it to the LastSyncAt field.
func (o *CalendarIntegration) SetLastSyncAt(v time.Time) {
	o.LastSyncAt = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *CalendarIntegration) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CalendarIntegration) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *CalendarIntegration) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *CalendarIntegration) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CalendarIntegration) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CalendarIntegration) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CalendarIntegration) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *CalendarIntegration) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *CalendarIntegration) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *CalendarIntegration) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o CalendarIntegration) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CalendarIntegration) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["provider"] = o.Provider
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	toSerialize["status"] = o.Status
	if !IsNil(o.LastSyncAt) {
		toSerialize["last_sync_at"] = o.LastSyncAt
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["error_message"] = o.ErrorMessage
	}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *CalendarIntegration) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"tenant_id",
		"provider",
		"status",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCalendarIntegration := _CalendarIntegration{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCalendarIntegration)

	if err != nil {
		return err
	}

	*o = CalendarIntegration(varCalendarIntegration)

	return err
}

type NullableCalendarIntegration struct {
	value *CalendarIntegration
	isSet bool
}

func (v NullableCalendarIntegration) Get() *CalendarIntegration {
	return v.value
}

func (v *NullableCalendarIntegration) Set(val *CalendarIntegration) {
	v.value = val
	v.isSet = true
}

func (v NullableCalendarIntegration) IsSet() bool {
	return v.isSet
}

func (v *NullableCalendarIntegration) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCalendarIntegration(val *CalendarIntegration) *NullableCalendarIntegration {
	return &NullableCalendarIntegration{value: val, isSet: true}
}

func (v NullableCalendarIntegration) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCalendarIntegration) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


