/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
)

// checks if the UpdateGALSettingsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateGALSettingsRequest{}

// UpdateGALSettingsRequest struct for UpdateGALSettingsRequest
type UpdateGALSettingsRequest struct {
	GalEnabled *bool `json:"gal_enabled,omitempty"`
	HideFromDirectory *bool `json:"hide_from_directory,omitempty"`
	DepartmentGrouping *bool `json:"department_grouping,omitempty"`
	SearchVisibility *string `json:"search_visibility,omitempty"`
	IncludeExternalContacts *bool `json:"include_external_contacts,omitempty"`
}

// NewUpdateGALSettingsRequest instantiates a new UpdateGALSettingsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateGALSettingsRequest() *UpdateGALSettingsRequest {
	this := UpdateGALSettingsRequest{}
	return &this
}

// NewUpdateGALSettingsRequestWithDefaults instantiates a new UpdateGALSettingsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateGALSettingsRequestWithDefaults() *UpdateGALSettingsRequest {
	this := UpdateGALSettingsRequest{}
	return &this
}

// GetGalEnabled returns the GalEnabled field value if set, zero value otherwise.
func (o *UpdateGALSettingsRequest) GetGalEnabled() bool {
	if o == nil || IsNil(o.GalEnabled) {
		var ret bool
		return ret
	}
	return *o.GalEnabled
}

// GetGalEnabledOk returns a tuple with the GalEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGALSettingsRequest) GetGalEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.GalEnabled) {
		return nil, false
	}
	return o.GalEnabled, true
}

// HasGalEnabled returns a boolean if a field has been set.
func (o *UpdateGALSettingsRequest) HasGalEnabled() bool {
	if o != nil && !IsNil(o.GalEnabled) {
		return true
	}

	return false
}

// SetGalEnabled gets a reference to the given bool and assigns it to the GalEnabled field.
func (o *UpdateGALSettingsRequest) SetGalEnabled(v bool) {
	o.GalEnabled = &v
}

// GetHideFromDirectory returns the HideFromDirectory field value if set, zero value otherwise.
func (o *UpdateGALSettingsRequest) GetHideFromDirectory() bool {
	if o == nil || IsNil(o.HideFromDirectory) {
		var ret bool
		return ret
	}
	return *o.HideFromDirectory
}

// GetHideFromDirectoryOk returns a tuple with the HideFromDirectory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGALSettingsRequest) GetHideFromDirectoryOk() (*bool, bool) {
	if o == nil || IsNil(o.HideFromDirectory) {
		return nil, false
	}
	return o.HideFromDirectory, true
}

// HasHideFromDirectory returns a boolean if a field has been set.
func (o *UpdateGALSettingsRequest) HasHideFromDirectory() bool {
	if o != nil && !IsNil(o.HideFromDirectory) {
		return true
	}

	return false
}

// SetHideFromDirectory gets a reference to the given bool and assigns it to the HideFromDirectory field.
func (o *UpdateGALSettingsRequest) SetHideFromDirectory(v bool) {
	o.HideFromDirectory = &v
}

// GetDepartmentGrouping returns the DepartmentGrouping field value if set, zero value otherwise.
func (o *UpdateGALSettingsRequest) GetDepartmentGrouping() bool {
	if o == nil || IsNil(o.DepartmentGrouping) {
		var ret bool
		return ret
	}
	return *o.DepartmentGrouping
}

// GetDepartmentGroupingOk returns a tuple with the DepartmentGrouping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGALSettingsRequest) GetDepartmentGroupingOk() (*bool, bool) {
	if o == nil || IsNil(o.DepartmentGrouping) {
		return nil, false
	}
	return o.DepartmentGrouping, true
}

// HasDepartmentGrouping returns a boolean if a field has been set.
func (o *UpdateGALSettingsRequest) HasDepartmentGrouping() bool {
	if o != nil && !IsNil(o.DepartmentGrouping) {
		return true
	}

	return false
}

// SetDepartmentGrouping gets a reference to the given bool and assigns it to the DepartmentGrouping field.
func (o *UpdateGALSettingsRequest) SetDepartmentGrouping(v bool) {
	o.DepartmentGrouping = &v
}

// GetSearchVisibility returns the SearchVisibility field value if set, zero value otherwise.
func (o *UpdateGALSettingsRequest) GetSearchVisibility() string {
	if o == nil || IsNil(o.SearchVisibility) {
		var ret string
		return ret
	}
	return *o.SearchVisibility
}

// GetSearchVisibilityOk returns a tuple with the SearchVisibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGALSettingsRequest) GetSearchVisibilityOk() (*string, bool) {
	if o == nil || IsNil(o.SearchVisibility) {
		return nil, false
	}
	return o.SearchVisibility, true
}

// HasSearchVisibility returns a boolean if a field has been set.
func (o *UpdateGALSettingsRequest) HasSearchVisibility() bool {
	if o != nil && !IsNil(o.SearchVisibility) {
		return true
	}

	return false
}

// SetSearchVisibility gets a reference to the given string and assigns it to the SearchVisibility field.
func (o *UpdateGALSettingsRequest) SetSearchVisibility(v string) {
	o.SearchVisibility = &v
}

// GetIncludeExternalContacts returns the IncludeExternalContacts field value if set, zero value otherwise.
func (o *UpdateGALSettingsRequest) GetIncludeExternalContacts() bool {
	if o == nil || IsNil(o.IncludeExternalContacts) {
		var ret bool
		return ret
	}
	return *o.IncludeExternalContacts
}

// GetIncludeExternalContactsOk returns a tuple with the IncludeExternalContacts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateGALSettingsRequest) GetIncludeExternalContactsOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeExternalContacts) {
		return nil, false
	}
	return o.IncludeExternalContacts, true
}

// HasIncludeExternalContacts returns a boolean if a field has been set.
func (o *UpdateGALSettingsRequest) HasIncludeExternalContacts() bool {
	if o != nil && !IsNil(o.IncludeExternalContacts) {
		return true
	}

	return false
}

// SetIncludeExternalContacts gets a reference to the given bool and assigns it to the IncludeExternalContacts field.
func (o *UpdateGALSettingsRequest) SetIncludeExternalContacts(v bool) {
	o.IncludeExternalContacts = &v
}

func (o UpdateGALSettingsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateGALSettingsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GalEnabled) {
		toSerialize["gal_enabled"] = o.GalEnabled
	}
	if !IsNil(o.HideFromDirectory) {
		toSerialize["hide_from_directory"] = o.HideFromDirectory
	}
	if !IsNil(o.DepartmentGrouping) {
		toSerialize["department_grouping"] = o.DepartmentGrouping
	}
	if !IsNil(o.SearchVisibility) {
		toSerialize["search_visibility"] = o.SearchVisibility
	}
	if !IsNil(o.IncludeExternalContacts) {
		toSerialize["include_external_contacts"] = o.IncludeExternalContacts
	}
	return toSerialize, nil
}

type NullableUpdateGALSettingsRequest struct {
	value *UpdateGALSettingsRequest
	isSet bool
}

func (v NullableUpdateGALSettingsRequest) Get() *UpdateGALSettingsRequest {
	return v.value
}

func (v *NullableUpdateGALSettingsRequest) Set(val *UpdateGALSettingsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateGALSettingsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateGALSettingsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateGALSettingsRequest(val *UpdateGALSettingsRequest) *NullableUpdateGALSettingsRequest {
	return &NullableUpdateGALSettingsRequest{value: val, isSet: true}
}

func (v NullableUpdateGALSettingsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateGALSettingsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


