/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"time"
)

// checks if the GetDirectoryActivity200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDirectoryActivity200ResponseDataInner{}

// GetDirectoryActivity200ResponseDataInner struct for GetDirectoryActivity200ResponseDataInner
type GetDirectoryActivity200ResponseDataInner struct {
	Type *string `json:"type,omitempty"`
	Message *string `json:"message,omitempty"`
	Detail *string `json:"detail,omitempty"`
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// NewGetDirectoryActivity200ResponseDataInner instantiates a new GetDirectoryActivity200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDirectoryActivity200ResponseDataInner() *GetDirectoryActivity200ResponseDataInner {
	this := GetDirectoryActivity200ResponseDataInner{}
	return &this
}

// NewGetDirectoryActivity200ResponseDataInnerWithDefaults instantiates a new GetDirectoryActivity200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDirectoryActivity200ResponseDataInnerWithDefaults() *GetDirectoryActivity200ResponseDataInner {
	this := GetDirectoryActivity200ResponseDataInner{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetDirectoryActivity200ResponseDataInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDirectoryActivity200ResponseDataInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetDirectoryActivity200ResponseDataInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetDirectoryActivity200ResponseDataInner) SetType(v string) {
	o.Type = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetDirectoryActivity200ResponseDataInner) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDirectoryActivity200ResponseDataInner) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetDirectoryActivity200ResponseDataInner) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetDirectoryActivity200ResponseDataInner) SetMessage(v string) {
	o.Message = &v
}

// GetDetail returns the Detail field value if set, zero value otherwise.
func (o *GetDirectoryActivity200ResponseDataInner) GetDetail() string {
	if o == nil || IsNil(o.Detail) {
		var ret string
		return ret
	}
	return *o.Detail
}

// GetDetailOk returns a tuple with the Detail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDirectoryActivity200ResponseDataInner) GetDetailOk() (*string, bool) {
	if o == nil || IsNil(o.Detail) {
		return nil, false
	}
	return o.Detail, true
}

// HasDetail returns a boolean if a field has been set.
func (o *GetDirectoryActivity200ResponseDataInner) HasDetail() bool {
	if o != nil && !IsNil(o.Detail) {
		return true
	}

	return false
}

// SetDetail gets a reference to the given string and assigns it to the Detail field.
func (o *GetDirectoryActivity200ResponseDataInner) SetDetail(v string) {
	o.Detail = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *GetDirectoryActivity200ResponseDataInner) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDirectoryActivity200ResponseDataInner) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *GetDirectoryActivity200ResponseDataInner) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *GetDirectoryActivity200ResponseDataInner) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

func (o GetDirectoryActivity200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDirectoryActivity200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Detail) {
		toSerialize["detail"] = o.Detail
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	return toSerialize, nil
}

type NullableGetDirectoryActivity200ResponseDataInner struct {
	value *GetDirectoryActivity200ResponseDataInner
	isSet bool
}

func (v NullableGetDirectoryActivity200ResponseDataInner) Get() *GetDirectoryActivity200ResponseDataInner {
	return v.value
}

func (v *NullableGetDirectoryActivity200ResponseDataInner) Set(val *GetDirectoryActivity200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDirectoryActivity200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDirectoryActivity200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDirectoryActivity200ResponseDataInner(val *GetDirectoryActivity200ResponseDataInner) *NullableGetDirectoryActivity200ResponseDataInner {
	return &NullableGetDirectoryActivity200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetDirectoryActivity200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDirectoryActivity200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


