/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListMigrationEvents200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListMigrationEvents200Response{}

// ListMigrationEvents200Response struct for ListMigrationEvents200Response
type ListMigrationEvents200Response struct {
	Data []MigrationEvent `json:"data"`
}

type _ListMigrationEvents200Response ListMigrationEvents200Response

// NewListMigrationEvents200Response instantiates a new ListMigrationEvents200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListMigrationEvents200Response(data []MigrationEvent) *ListMigrationEvents200Response {
	this := ListMigrationEvents200Response{}
	this.Data = data
	return &this
}

// NewListMigrationEvents200ResponseWithDefaults instantiates a new ListMigrationEvents200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListMigrationEvents200ResponseWithDefaults() *ListMigrationEvents200Response {
	this := ListMigrationEvents200Response{}
	return &this
}

// GetData returns the Data field value
func (o *ListMigrationEvents200Response) GetData() []MigrationEvent {
	if o == nil {
		var ret []MigrationEvent
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListMigrationEvents200Response) GetDataOk() ([]MigrationEvent, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListMigrationEvents200Response) SetData(v []MigrationEvent) {
	o.Data = v
}

func (o ListMigrationEvents200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListMigrationEvents200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ListMigrationEvents200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListMigrationEvents200Response := _ListMigrationEvents200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListMigrationEvents200Response)

	if err != nil {
		return err
	}

	*o = ListMigrationEvents200Response(varListMigrationEvents200Response)

	return err
}

type NullableListMigrationEvents200Response struct {
	value *ListMigrationEvents200Response
	isSet bool
}

func (v NullableListMigrationEvents200Response) Get() *ListMigrationEvents200Response {
	return v.value
}

func (v *NullableListMigrationEvents200Response) Set(val *ListMigrationEvents200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListMigrationEvents200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListMigrationEvents200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListMigrationEvents200Response(val *ListMigrationEvents200Response) *NullableListMigrationEvents200Response {
	return &NullableListMigrationEvents200Response{value: val, isSet: true}
}

func (v NullableListMigrationEvents200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListMigrationEvents200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


