/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddCalendarMemberRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddCalendarMemberRequest{}

// AddCalendarMemberRequest struct for AddCalendarMemberRequest
type AddCalendarMemberRequest struct {
	UserEmail string `json:"user_email"`
	Role *string `json:"role,omitempty"`
}

type _AddCalendarMemberRequest AddCalendarMemberRequest

// NewAddCalendarMemberRequest instantiates a new AddCalendarMemberRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddCalendarMemberRequest(userEmail string) *AddCalendarMemberRequest {
	this := AddCalendarMemberRequest{}
	this.UserEmail = userEmail
	var role string = "viewer"
	this.Role = &role
	return &this
}

// NewAddCalendarMemberRequestWithDefaults instantiates a new AddCalendarMemberRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddCalendarMemberRequestWithDefaults() *AddCalendarMemberRequest {
	this := AddCalendarMemberRequest{}
	var role string = "viewer"
	this.Role = &role
	return &this
}

// GetUserEmail returns the UserEmail field value
func (o *AddCalendarMemberRequest) GetUserEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserEmail
}

// GetUserEmailOk returns a tuple with the UserEmail field value
// and a boolean to check if the value has been set.
func (o *AddCalendarMemberRequest) GetUserEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserEmail, true
}

// SetUserEmail sets field value
func (o *AddCalendarMemberRequest) SetUserEmail(v string) {
	o.UserEmail = v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *AddCalendarMemberRequest) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddCalendarMemberRequest) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *AddCalendarMemberRequest) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *AddCalendarMemberRequest) SetRole(v string) {
	o.Role = &v
}

func (o AddCalendarMemberRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddCalendarMemberRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["user_email"] = o.UserEmail
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

func (o *AddCalendarMemberRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"user_email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddCalendarMemberRequest := _AddCalendarMemberRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddCalendarMemberRequest)

	if err != nil {
		return err
	}

	*o = AddCalendarMemberRequest(varAddCalendarMemberRequest)

	return err
}

type NullableAddCalendarMemberRequest struct {
	value *AddCalendarMemberRequest
	isSet bool
}

func (v NullableAddCalendarMemberRequest) Get() *AddCalendarMemberRequest {
	return v.value
}

func (v *NullableAddCalendarMemberRequest) Set(val *AddCalendarMemberRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddCalendarMemberRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddCalendarMemberRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddCalendarMemberRequest(val *AddCalendarMemberRequest) *NullableAddCalendarMemberRequest {
	return &NullableAddCalendarMemberRequest{value: val, isSet: true}
}

func (v NullableAddCalendarMemberRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddCalendarMemberRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


