/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateEncryptionKeyRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEncryptionKeyRequest{}

// CreateEncryptionKeyRequest struct for CreateEncryptionKeyRequest
type CreateEncryptionKeyRequest struct {
	MailboxEmail string `json:"mailbox_email"`
	PublicKey string `json:"public_key"`
	EncryptedPrivateKey string `json:"encrypted_private_key"`
	KdfParams map[string]interface{} `json:"kdf_params,omitempty"`
}

type _CreateEncryptionKeyRequest CreateEncryptionKeyRequest

// NewCreateEncryptionKeyRequest instantiates a new CreateEncryptionKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEncryptionKeyRequest(mailboxEmail string, publicKey string, encryptedPrivateKey string) *CreateEncryptionKeyRequest {
	this := CreateEncryptionKeyRequest{}
	this.MailboxEmail = mailboxEmail
	this.PublicKey = publicKey
	this.EncryptedPrivateKey = encryptedPrivateKey
	return &this
}

// NewCreateEncryptionKeyRequestWithDefaults instantiates a new CreateEncryptionKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEncryptionKeyRequestWithDefaults() *CreateEncryptionKeyRequest {
	this := CreateEncryptionKeyRequest{}
	return &this
}

// GetMailboxEmail returns the MailboxEmail field value
func (o *CreateEncryptionKeyRequest) GetMailboxEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MailboxEmail
}

// GetMailboxEmailOk returns a tuple with the MailboxEmail field value
// and a boolean to check if the value has been set.
func (o *CreateEncryptionKeyRequest) GetMailboxEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MailboxEmail, true
}

// SetMailboxEmail sets field value
func (o *CreateEncryptionKeyRequest) SetMailboxEmail(v string) {
	o.MailboxEmail = v
}

// GetPublicKey returns the PublicKey field value
func (o *CreateEncryptionKeyRequest) GetPublicKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PublicKey
}

// GetPublicKeyOk returns a tuple with the PublicKey field value
// and a boolean to check if the value has been set.
func (o *CreateEncryptionKeyRequest) GetPublicKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PublicKey, true
}

// SetPublicKey sets field value
func (o *CreateEncryptionKeyRequest) SetPublicKey(v string) {
	o.PublicKey = v
}

// GetEncryptedPrivateKey returns the EncryptedPrivateKey field value
func (o *CreateEncryptionKeyRequest) GetEncryptedPrivateKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EncryptedPrivateKey
}

// GetEncryptedPrivateKeyOk returns a tuple with the EncryptedPrivateKey field value
// and a boolean to check if the value has been set.
func (o *CreateEncryptionKeyRequest) GetEncryptedPrivateKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EncryptedPrivateKey, true
}

// SetEncryptedPrivateKey sets field value
func (o *CreateEncryptionKeyRequest) SetEncryptedPrivateKey(v string) {
	o.EncryptedPrivateKey = v
}

// GetKdfParams returns the KdfParams field value if set, zero value otherwise.
func (o *CreateEncryptionKeyRequest) GetKdfParams() map[string]interface{} {
	if o == nil || IsNil(o.KdfParams) {
		var ret map[string]interface{}
		return ret
	}
	return o.KdfParams
}

// GetKdfParamsOk returns a tuple with the KdfParams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateEncryptionKeyRequest) GetKdfParamsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.KdfParams) {
		return map[string]interface{}{}, false
	}
	return o.KdfParams, true
}

// HasKdfParams returns a boolean if a field has been set.
func (o *CreateEncryptionKeyRequest) HasKdfParams() bool {
	if o != nil && !IsNil(o.KdfParams) {
		return true
	}

	return false
}

// SetKdfParams gets a reference to the given map[string]interface{} and assigns it to the KdfParams field.
func (o *CreateEncryptionKeyRequest) SetKdfParams(v map[string]interface{}) {
	o.KdfParams = v
}

func (o CreateEncryptionKeyRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEncryptionKeyRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mailbox_email"] = o.MailboxEmail
	toSerialize["public_key"] = o.PublicKey
	toSerialize["encrypted_private_key"] = o.EncryptedPrivateKey
	if !IsNil(o.KdfParams) {
		toSerialize["kdf_params"] = o.KdfParams
	}
	return toSerialize, nil
}

func (o *CreateEncryptionKeyRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mailbox_email",
		"public_key",
		"encrypted_private_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEncryptionKeyRequest := _CreateEncryptionKeyRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateEncryptionKeyRequest)

	if err != nil {
		return err
	}

	*o = CreateEncryptionKeyRequest(varCreateEncryptionKeyRequest)

	return err
}

type NullableCreateEncryptionKeyRequest struct {
	value *CreateEncryptionKeyRequest
	isSet bool
}

func (v NullableCreateEncryptionKeyRequest) Get() *CreateEncryptionKeyRequest {
	return v.value
}

func (v *NullableCreateEncryptionKeyRequest) Set(val *CreateEncryptionKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEncryptionKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEncryptionKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEncryptionKeyRequest(val *CreateEncryptionKeyRequest) *NullableCreateEncryptionKeyRequest {
	return &NullableCreateEncryptionKeyRequest{value: val, isSet: true}
}

func (v NullableCreateEncryptionKeyRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEncryptionKeyRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


