/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MapMigrationRequestMappingsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MapMigrationRequestMappingsInner{}

// MapMigrationRequestMappingsInner struct for MapMigrationRequestMappingsInner
type MapMigrationRequestMappingsInner struct {
	SourceEmail string `json:"source_email"`
	DestEmail string `json:"dest_email"`
}

type _MapMigrationRequestMappingsInner MapMigrationRequestMappingsInner

// NewMapMigrationRequestMappingsInner instantiates a new MapMigrationRequestMappingsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMapMigrationRequestMappingsInner(sourceEmail string, destEmail string) *MapMigrationRequestMappingsInner {
	this := MapMigrationRequestMappingsInner{}
	this.SourceEmail = sourceEmail
	this.DestEmail = destEmail
	return &this
}

// NewMapMigrationRequestMappingsInnerWithDefaults instantiates a new MapMigrationRequestMappingsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMapMigrationRequestMappingsInnerWithDefaults() *MapMigrationRequestMappingsInner {
	this := MapMigrationRequestMappingsInner{}
	return &this
}

// GetSourceEmail returns the SourceEmail field value
func (o *MapMigrationRequestMappingsInner) GetSourceEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceEmail
}

// GetSourceEmailOk returns a tuple with the SourceEmail field value
// and a boolean to check if the value has been set.
func (o *MapMigrationRequestMappingsInner) GetSourceEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceEmail, true
}

// SetSourceEmail sets field value
func (o *MapMigrationRequestMappingsInner) SetSourceEmail(v string) {
	o.SourceEmail = v
}

// GetDestEmail returns the DestEmail field value
func (o *MapMigrationRequestMappingsInner) GetDestEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestEmail
}

// GetDestEmailOk returns a tuple with the DestEmail field value
// and a boolean to check if the value has been set.
func (o *MapMigrationRequestMappingsInner) GetDestEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestEmail, true
}

// SetDestEmail sets field value
func (o *MapMigrationRequestMappingsInner) SetDestEmail(v string) {
	o.DestEmail = v
}

func (o MapMigrationRequestMappingsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MapMigrationRequestMappingsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["source_email"] = o.SourceEmail
	toSerialize["dest_email"] = o.DestEmail
	return toSerialize, nil
}

func (o *MapMigrationRequestMappingsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"source_email",
		"dest_email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMapMigrationRequestMappingsInner := _MapMigrationRequestMappingsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMapMigrationRequestMappingsInner)

	if err != nil {
		return err
	}

	*o = MapMigrationRequestMappingsInner(varMapMigrationRequestMappingsInner)

	return err
}

type NullableMapMigrationRequestMappingsInner struct {
	value *MapMigrationRequestMappingsInner
	isSet bool
}

func (v NullableMapMigrationRequestMappingsInner) Get() *MapMigrationRequestMappingsInner {
	return v.value
}

func (v *NullableMapMigrationRequestMappingsInner) Set(val *MapMigrationRequestMappingsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMapMigrationRequestMappingsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMapMigrationRequestMappingsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMapMigrationRequestMappingsInner(val *MapMigrationRequestMappingsInner) *NullableMapMigrationRequestMappingsInner {
	return &NullableMapMigrationRequestMappingsInner{value: val, isSet: true}
}

func (v NullableMapMigrationRequestMappingsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMapMigrationRequestMappingsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


