/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1MailboxesEmailVacationPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1MailboxesEmailVacationPutRequest{}

// V1MailboxesEmailVacationPutRequest struct for V1MailboxesEmailVacationPutRequest
type V1MailboxesEmailVacationPutRequest struct {
	Enabled *bool `json:"enabled,omitempty"`
	Params VacationParams `json:"params"`
}

type _V1MailboxesEmailVacationPutRequest V1MailboxesEmailVacationPutRequest

// NewV1MailboxesEmailVacationPutRequest instantiates a new V1MailboxesEmailVacationPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1MailboxesEmailVacationPutRequest(params VacationParams) *V1MailboxesEmailVacationPutRequest {
	this := V1MailboxesEmailVacationPutRequest{}
	var enabled bool = true
	this.Enabled = &enabled
	this.Params = params
	return &this
}

// NewV1MailboxesEmailVacationPutRequestWithDefaults instantiates a new V1MailboxesEmailVacationPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1MailboxesEmailVacationPutRequestWithDefaults() *V1MailboxesEmailVacationPutRequest {
	this := V1MailboxesEmailVacationPutRequest{}
	var enabled bool = true
	this.Enabled = &enabled
	return &this
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *V1MailboxesEmailVacationPutRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1MailboxesEmailVacationPutRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *V1MailboxesEmailVacationPutRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *V1MailboxesEmailVacationPutRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetParams returns the Params field value
func (o *V1MailboxesEmailVacationPutRequest) GetParams() VacationParams {
	if o == nil {
		var ret VacationParams
		return ret
	}

	return o.Params
}

// GetParamsOk returns a tuple with the Params field value
// and a boolean to check if the value has been set.
func (o *V1MailboxesEmailVacationPutRequest) GetParamsOk() (*VacationParams, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Params, true
}

// SetParams sets field value
func (o *V1MailboxesEmailVacationPutRequest) SetParams(v VacationParams) {
	o.Params = v
}

func (o V1MailboxesEmailVacationPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1MailboxesEmailVacationPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	toSerialize["params"] = o.Params
	return toSerialize, nil
}

func (o *V1MailboxesEmailVacationPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"params",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1MailboxesEmailVacationPutRequest := _V1MailboxesEmailVacationPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1MailboxesEmailVacationPutRequest)

	if err != nil {
		return err
	}

	*o = V1MailboxesEmailVacationPutRequest(varV1MailboxesEmailVacationPutRequest)

	return err
}

type NullableV1MailboxesEmailVacationPutRequest struct {
	value *V1MailboxesEmailVacationPutRequest
	isSet bool
}

func (v NullableV1MailboxesEmailVacationPutRequest) Get() *V1MailboxesEmailVacationPutRequest {
	return v.value
}

func (v *NullableV1MailboxesEmailVacationPutRequest) Set(val *V1MailboxesEmailVacationPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1MailboxesEmailVacationPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1MailboxesEmailVacationPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1MailboxesEmailVacationPutRequest(val *V1MailboxesEmailVacationPutRequest) *NullableV1MailboxesEmailVacationPutRequest {
	return &NullableV1MailboxesEmailVacationPutRequest{value: val, isSet: true}
}

func (v NullableV1MailboxesEmailVacationPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1MailboxesEmailVacationPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


