/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateResourceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateResourceRequest{}

// CreateResourceRequest struct for CreateResourceRequest
type CreateResourceRequest struct {
	Name string `json:"name"`
	Type *string `json:"type,omitempty"`
	Capacity *int32 `json:"capacity,omitempty"`
}

type _CreateResourceRequest CreateResourceRequest

// NewCreateResourceRequest instantiates a new CreateResourceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateResourceRequest(name string) *CreateResourceRequest {
	this := CreateResourceRequest{}
	this.Name = name
	var type_ string = "meeting_room"
	this.Type = &type_
	return &this
}

// NewCreateResourceRequestWithDefaults instantiates a new CreateResourceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateResourceRequestWithDefaults() *CreateResourceRequest {
	this := CreateResourceRequest{}
	var type_ string = "meeting_room"
	this.Type = &type_
	return &this
}

// GetName returns the Name field value
func (o *CreateResourceRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateResourceRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateResourceRequest) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateResourceRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateResourceRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateResourceRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateResourceRequest) SetType(v string) {
	o.Type = &v
}

// GetCapacity returns the Capacity field value if set, zero value otherwise.
func (o *CreateResourceRequest) GetCapacity() int32 {
	if o == nil || IsNil(o.Capacity) {
		var ret int32
		return ret
	}
	return *o.Capacity
}

// GetCapacityOk returns a tuple with the Capacity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateResourceRequest) GetCapacityOk() (*int32, bool) {
	if o == nil || IsNil(o.Capacity) {
		return nil, false
	}
	return o.Capacity, true
}

// HasCapacity returns a boolean if a field has been set.
func (o *CreateResourceRequest) HasCapacity() bool {
	if o != nil && !IsNil(o.Capacity) {
		return true
	}

	return false
}

// SetCapacity gets a reference to the given int32 and assigns it to the Capacity field.
func (o *CreateResourceRequest) SetCapacity(v int32) {
	o.Capacity = &v
}

func (o CreateResourceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateResourceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Capacity) {
		toSerialize["capacity"] = o.Capacity
	}
	return toSerialize, nil
}

func (o *CreateResourceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateResourceRequest := _CreateResourceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateResourceRequest)

	if err != nil {
		return err
	}

	*o = CreateResourceRequest(varCreateResourceRequest)

	return err
}

type NullableCreateResourceRequest struct {
	value *CreateResourceRequest
	isSet bool
}

func (v NullableCreateResourceRequest) Get() *CreateResourceRequest {
	return v.value
}

func (v *NullableCreateResourceRequest) Set(val *CreateResourceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateResourceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateResourceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateResourceRequest(val *CreateResourceRequest) *NullableCreateResourceRequest {
	return &NullableCreateResourceRequest{value: val, isSet: true}
}

func (v NullableCreateResourceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateResourceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


