/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateBillingCheckoutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBillingCheckoutRequest{}

// CreateBillingCheckoutRequest struct for CreateBillingCheckoutRequest
type CreateBillingCheckoutRequest struct {
	Plan string `json:"plan"`
}

type _CreateBillingCheckoutRequest CreateBillingCheckoutRequest

// NewCreateBillingCheckoutRequest instantiates a new CreateBillingCheckoutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBillingCheckoutRequest(plan string) *CreateBillingCheckoutRequest {
	this := CreateBillingCheckoutRequest{}
	this.Plan = plan
	return &this
}

// NewCreateBillingCheckoutRequestWithDefaults instantiates a new CreateBillingCheckoutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBillingCheckoutRequestWithDefaults() *CreateBillingCheckoutRequest {
	this := CreateBillingCheckoutRequest{}
	return &this
}

// GetPlan returns the Plan field value
func (o *CreateBillingCheckoutRequest) GetPlan() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Plan
}

// GetPlanOk returns a tuple with the Plan field value
// and a boolean to check if the value has been set.
func (o *CreateBillingCheckoutRequest) GetPlanOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Plan, true
}

// SetPlan sets field value
func (o *CreateBillingCheckoutRequest) SetPlan(v string) {
	o.Plan = v
}

func (o CreateBillingCheckoutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBillingCheckoutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["plan"] = o.Plan
	return toSerialize, nil
}

func (o *CreateBillingCheckoutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"plan",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBillingCheckoutRequest := _CreateBillingCheckoutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateBillingCheckoutRequest)

	if err != nil {
		return err
	}

	*o = CreateBillingCheckoutRequest(varCreateBillingCheckoutRequest)

	return err
}

type NullableCreateBillingCheckoutRequest struct {
	value *CreateBillingCheckoutRequest
	isSet bool
}

func (v NullableCreateBillingCheckoutRequest) Get() *CreateBillingCheckoutRequest {
	return v.value
}

func (v *NullableCreateBillingCheckoutRequest) Set(val *CreateBillingCheckoutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBillingCheckoutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBillingCheckoutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBillingCheckoutRequest(val *CreateBillingCheckoutRequest) *NullableCreateBillingCheckoutRequest {
	return &NullableCreateBillingCheckoutRequest{value: val, isSet: true}
}

func (v NullableCreateBillingCheckoutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBillingCheckoutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


