/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
)

// checks if the V1MailboxesEmailPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1MailboxesEmailPatchRequest{}

// V1MailboxesEmailPatchRequest struct for V1MailboxesEmailPatchRequest
type V1MailboxesEmailPatchRequest struct {
	Password *string `json:"password,omitempty"`
	QuotaBytes *int64 `json:"quota_bytes,omitempty"`
	Disabled *bool `json:"disabled,omitempty"`
}

// NewV1MailboxesEmailPatchRequest instantiates a new V1MailboxesEmailPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1MailboxesEmailPatchRequest() *V1MailboxesEmailPatchRequest {
	this := V1MailboxesEmailPatchRequest{}
	return &this
}

// NewV1MailboxesEmailPatchRequestWithDefaults instantiates a new V1MailboxesEmailPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1MailboxesEmailPatchRequestWithDefaults() *V1MailboxesEmailPatchRequest {
	this := V1MailboxesEmailPatchRequest{}
	return &this
}

// GetPassword returns the Password field value if set, zero value otherwise.
func (o *V1MailboxesEmailPatchRequest) GetPassword() string {
	if o == nil || IsNil(o.Password) {
		var ret string
		return ret
	}
	return *o.Password
}

// GetPasswordOk returns a tuple with the Password field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1MailboxesEmailPatchRequest) GetPasswordOk() (*string, bool) {
	if o == nil || IsNil(o.Password) {
		return nil, false
	}
	return o.Password, true
}

// HasPassword returns a boolean if a field has been set.
func (o *V1MailboxesEmailPatchRequest) HasPassword() bool {
	if o != nil && !IsNil(o.Password) {
		return true
	}

	return false
}

// SetPassword gets a reference to the given string and assigns it to the Password field.
func (o *V1MailboxesEmailPatchRequest) SetPassword(v string) {
	o.Password = &v
}

// GetQuotaBytes returns the QuotaBytes field value if set, zero value otherwise.
func (o *V1MailboxesEmailPatchRequest) GetQuotaBytes() int64 {
	if o == nil || IsNil(o.QuotaBytes) {
		var ret int64
		return ret
	}
	return *o.QuotaBytes
}

// GetQuotaBytesOk returns a tuple with the QuotaBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1MailboxesEmailPatchRequest) GetQuotaBytesOk() (*int64, bool) {
	if o == nil || IsNil(o.QuotaBytes) {
		return nil, false
	}
	return o.QuotaBytes, true
}

// HasQuotaBytes returns a boolean if a field has been set.
func (o *V1MailboxesEmailPatchRequest) HasQuotaBytes() bool {
	if o != nil && !IsNil(o.QuotaBytes) {
		return true
	}

	return false
}

// SetQuotaBytes gets a reference to the given int64 and assigns it to the QuotaBytes field.
func (o *V1MailboxesEmailPatchRequest) SetQuotaBytes(v int64) {
	o.QuotaBytes = &v
}

// GetDisabled returns the Disabled field value if set, zero value otherwise.
func (o *V1MailboxesEmailPatchRequest) GetDisabled() bool {
	if o == nil || IsNil(o.Disabled) {
		var ret bool
		return ret
	}
	return *o.Disabled
}

// GetDisabledOk returns a tuple with the Disabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1MailboxesEmailPatchRequest) GetDisabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Disabled) {
		return nil, false
	}
	return o.Disabled, true
}

// HasDisabled returns a boolean if a field has been set.
func (o *V1MailboxesEmailPatchRequest) HasDisabled() bool {
	if o != nil && !IsNil(o.Disabled) {
		return true
	}

	return false
}

// SetDisabled gets a reference to the given bool and assigns it to the Disabled field.
func (o *V1MailboxesEmailPatchRequest) SetDisabled(v bool) {
	o.Disabled = &v
}

func (o V1MailboxesEmailPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1MailboxesEmailPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Password) {
		toSerialize["password"] = o.Password
	}
	if !IsNil(o.QuotaBytes) {
		toSerialize["quota_bytes"] = o.QuotaBytes
	}
	if !IsNil(o.Disabled) {
		toSerialize["disabled"] = o.Disabled
	}
	return toSerialize, nil
}

type NullableV1MailboxesEmailPatchRequest struct {
	value *V1MailboxesEmailPatchRequest
	isSet bool
}

func (v NullableV1MailboxesEmailPatchRequest) Get() *V1MailboxesEmailPatchRequest {
	return v.value
}

func (v *NullableV1MailboxesEmailPatchRequest) Set(val *V1MailboxesEmailPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV1MailboxesEmailPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV1MailboxesEmailPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1MailboxesEmailPatchRequest(val *V1MailboxesEmailPatchRequest) *NullableV1MailboxesEmailPatchRequest {
	return &NullableV1MailboxesEmailPatchRequest{value: val, isSet: true}
}

func (v NullableV1MailboxesEmailPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1MailboxesEmailPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


