/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateDedicatedIPRequestRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDedicatedIPRequestRequest{}

// CreateDedicatedIPRequestRequest struct for CreateDedicatedIPRequestRequest
type CreateDedicatedIPRequestRequest struct {
	Note string `json:"note"`
}

type _CreateDedicatedIPRequestRequest CreateDedicatedIPRequestRequest

// NewCreateDedicatedIPRequestRequest instantiates a new CreateDedicatedIPRequestRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDedicatedIPRequestRequest(note string) *CreateDedicatedIPRequestRequest {
	this := CreateDedicatedIPRequestRequest{}
	this.Note = note
	return &this
}

// NewCreateDedicatedIPRequestRequestWithDefaults instantiates a new CreateDedicatedIPRequestRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDedicatedIPRequestRequestWithDefaults() *CreateDedicatedIPRequestRequest {
	this := CreateDedicatedIPRequestRequest{}
	return &this
}

// GetNote returns the Note field value
func (o *CreateDedicatedIPRequestRequest) GetNote() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Note
}

// GetNoteOk returns a tuple with the Note field value
// and a boolean to check if the value has been set.
func (o *CreateDedicatedIPRequestRequest) GetNoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Note, true
}

// SetNote sets field value
func (o *CreateDedicatedIPRequestRequest) SetNote(v string) {
	o.Note = v
}

func (o CreateDedicatedIPRequestRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDedicatedIPRequestRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["note"] = o.Note
	return toSerialize, nil
}

func (o *CreateDedicatedIPRequestRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"note",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDedicatedIPRequestRequest := _CreateDedicatedIPRequestRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDedicatedIPRequestRequest)

	if err != nil {
		return err
	}

	*o = CreateDedicatedIPRequestRequest(varCreateDedicatedIPRequestRequest)

	return err
}

type NullableCreateDedicatedIPRequestRequest struct {
	value *CreateDedicatedIPRequestRequest
	isSet bool
}

func (v NullableCreateDedicatedIPRequestRequest) Get() *CreateDedicatedIPRequestRequest {
	return v.value
}

func (v *NullableCreateDedicatedIPRequestRequest) Set(val *CreateDedicatedIPRequestRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDedicatedIPRequestRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDedicatedIPRequestRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDedicatedIPRequestRequest(val *CreateDedicatedIPRequestRequest) *NullableCreateDedicatedIPRequestRequest {
	return &NullableCreateDedicatedIPRequestRequest{value: val, isSet: true}
}

func (v NullableCreateDedicatedIPRequestRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDedicatedIPRequestRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


