/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Domain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Domain{}

// Domain struct for Domain
type Domain struct {
	Id string `json:"id"`
	TenantId string `json:"tenant_id"`
	Domain string `json:"domain"`
	VerificationToken string `json:"verification_token"`
	Verified bool `json:"verified"`
	VerifiedAt *time.Time `json:"verified_at,omitempty"`
	DkimSelector string `json:"dkim_selector"`
	DkimPublicRecord string `json:"dkim_public_record"`
	CreatedAt time.Time `json:"created_at"`
	// DNS records the tenant must publish under their own DNS.
	Records []DNSRecord `json:"records,omitempty"`
}

type _Domain Domain

// NewDomain instantiates a new Domain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomain(id string, tenantId string, domain string, verificationToken string, verified bool, dkimSelector string, dkimPublicRecord string, createdAt time.Time) *Domain {
	this := Domain{}
	this.Id = id
	this.TenantId = tenantId
	this.Domain = domain
	this.VerificationToken = verificationToken
	this.Verified = verified
	this.DkimSelector = dkimSelector
	this.DkimPublicRecord = dkimPublicRecord
	this.CreatedAt = createdAt
	return &this
}

// NewDomainWithDefaults instantiates a new Domain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainWithDefaults() *Domain {
	this := Domain{}
	return &this
}

// GetId returns the Id field value
func (o *Domain) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Domain) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Domain) SetId(v string) {
	o.Id = v
}

// GetTenantId returns the TenantId field value
func (o *Domain) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *Domain) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *Domain) SetTenantId(v string) {
	o.TenantId = v
}

// GetDomain returns the Domain field value
func (o *Domain) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *Domain) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *Domain) SetDomain(v string) {
	o.Domain = v
}

// GetVerificationToken returns the VerificationToken field value
func (o *Domain) GetVerificationToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.VerificationToken
}

// GetVerificationTokenOk returns a tuple with the VerificationToken field value
// and a boolean to check if the value has been set.
func (o *Domain) GetVerificationTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VerificationToken, true
}

// SetVerificationToken sets field value
func (o *Domain) SetVerificationToken(v string) {
	o.VerificationToken = v
}

// GetVerified returns the Verified field value
func (o *Domain) GetVerified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Verified
}

// GetVerifiedOk returns a tuple with the Verified field value
// and a boolean to check if the value has been set.
func (o *Domain) GetVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Verified, true
}

// SetVerified sets field value
func (o *Domain) SetVerified(v bool) {
	o.Verified = v
}

// GetVerifiedAt returns the VerifiedAt field value if set, zero value otherwise.
func (o *Domain) GetVerifiedAt() time.Time {
	if o == nil || IsNil(o.VerifiedAt) {
		var ret time.Time
		return ret
	}
	return *o.VerifiedAt
}

// GetVerifiedAtOk returns a tuple with the VerifiedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Domain) GetVerifiedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.VerifiedAt) {
		return nil, false
	}
	return o.VerifiedAt, true
}

// HasVerifiedAt returns a boolean if a field has been set.
func (o *Domain) HasVerifiedAt() bool {
	if o != nil && !IsNil(o.VerifiedAt) {
		return true
	}

	return false
}

// SetVerifiedAt gets a reference to the given time.Time and assigns it to the VerifiedAt field.
func (o *Domain) SetVerifiedAt(v time.Time) {
	o.VerifiedAt = &v
}

// GetDkimSelector returns the DkimSelector field value
func (o *Domain) GetDkimSelector() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DkimSelector
}

// GetDkimSelectorOk returns a tuple with the DkimSelector field value
// and a boolean to check if the value has been set.
func (o *Domain) GetDkimSelectorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DkimSelector, true
}

// SetDkimSelector sets field value
func (o *Domain) SetDkimSelector(v string) {
	o.DkimSelector = v
}

// GetDkimPublicRecord returns the DkimPublicRecord field value
func (o *Domain) GetDkimPublicRecord() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DkimPublicRecord
}

// GetDkimPublicRecordOk returns a tuple with the DkimPublicRecord field value
// and a boolean to check if the value has been set.
func (o *Domain) GetDkimPublicRecordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DkimPublicRecord, true
}

// SetDkimPublicRecord sets field value
func (o *Domain) SetDkimPublicRecord(v string) {
	o.DkimPublicRecord = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Domain) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Domain) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Domain) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetRecords returns the Records field value if set, zero value otherwise.
func (o *Domain) GetRecords() []DNSRecord {
	if o == nil || IsNil(o.Records) {
		var ret []DNSRecord
		return ret
	}
	return o.Records
}

// GetRecordsOk returns a tuple with the Records field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Domain) GetRecordsOk() ([]DNSRecord, bool) {
	if o == nil || IsNil(o.Records) {
		return nil, false
	}
	return o.Records, true
}

// HasRecords returns a boolean if a field has been set.
func (o *Domain) HasRecords() bool {
	if o != nil && !IsNil(o.Records) {
		return true
	}

	return false
}

// SetRecords gets a reference to the given []DNSRecord and assigns it to the Records field.
func (o *Domain) SetRecords(v []DNSRecord) {
	o.Records = v
}

func (o Domain) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Domain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["domain"] = o.Domain
	toSerialize["verification_token"] = o.VerificationToken
	toSerialize["verified"] = o.Verified
	if !IsNil(o.VerifiedAt) {
		toSerialize["verified_at"] = o.VerifiedAt
	}
	toSerialize["dkim_selector"] = o.DkimSelector
	toSerialize["dkim_public_record"] = o.DkimPublicRecord
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.Records) {
		toSerialize["records"] = o.Records
	}
	return toSerialize, nil
}

func (o *Domain) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"tenant_id",
		"domain",
		"verification_token",
		"verified",
		"dkim_selector",
		"dkim_public_record",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomain := _Domain{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDomain)

	if err != nil {
		return err
	}

	*o = Domain(varDomain)

	return err
}

type NullableDomain struct {
	value *Domain
	isSet bool
}

func (v NullableDomain) Get() *Domain {
	return v.value
}

func (v *NullableDomain) Set(val *Domain) {
	v.value = val
	v.isSet = true
}

func (v NullableDomain) IsSet() bool {
	return v.isSet
}

func (v *NullableDomain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomain(val *Domain) *NullableDomain {
	return &NullableDomain{value: val, isSet: true}
}

func (v NullableDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


