/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
)

// checks if the ListContactLists200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListContactLists200Response{}

// ListContactLists200Response struct for ListContactLists200Response
type ListContactLists200Response struct {
	Data []ContactList `json:"data,omitempty"`
}

// NewListContactLists200Response instantiates a new ListContactLists200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListContactLists200Response() *ListContactLists200Response {
	this := ListContactLists200Response{}
	return &this
}

// NewListContactLists200ResponseWithDefaults instantiates a new ListContactLists200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListContactLists200ResponseWithDefaults() *ListContactLists200Response {
	this := ListContactLists200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListContactLists200Response) GetData() []ContactList {
	if o == nil || IsNil(o.Data) {
		var ret []ContactList
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListContactLists200Response) GetDataOk() ([]ContactList, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListContactLists200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ContactList and assigns it to the Data field.
func (o *ListContactLists200Response) SetData(v []ContactList) {
	o.Data = v
}

func (o ListContactLists200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListContactLists200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableListContactLists200Response struct {
	value *ListContactLists200Response
	isSet bool
}

func (v NullableListContactLists200Response) Get() *ListContactLists200Response {
	return v.value
}

func (v *NullableListContactLists200Response) Set(val *ListContactLists200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListContactLists200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListContactLists200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListContactLists200Response(val *ListContactLists200Response) *NullableListContactLists200Response {
	return &NullableListContactLists200Response{value: val, isSet: true}
}

func (v NullableListContactLists200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListContactLists200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


