/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
)

// checks if the V1SuppressionsGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1SuppressionsGet200Response{}

// V1SuppressionsGet200Response struct for V1SuppressionsGet200Response
type V1SuppressionsGet200Response struct {
	Data []Suppression `json:"data,omitempty"`
	NextCursor *string `json:"next_cursor,omitempty"`
}

// NewV1SuppressionsGet200Response instantiates a new V1SuppressionsGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1SuppressionsGet200Response() *V1SuppressionsGet200Response {
	this := V1SuppressionsGet200Response{}
	return &this
}

// NewV1SuppressionsGet200ResponseWithDefaults instantiates a new V1SuppressionsGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1SuppressionsGet200ResponseWithDefaults() *V1SuppressionsGet200Response {
	this := V1SuppressionsGet200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *V1SuppressionsGet200Response) GetData() []Suppression {
	if o == nil || IsNil(o.Data) {
		var ret []Suppression
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SuppressionsGet200Response) GetDataOk() ([]Suppression, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *V1SuppressionsGet200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Suppression and assigns it to the Data field.
func (o *V1SuppressionsGet200Response) SetData(v []Suppression) {
	o.Data = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *V1SuppressionsGet200Response) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1SuppressionsGet200Response) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *V1SuppressionsGet200Response) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *V1SuppressionsGet200Response) SetNextCursor(v string) {
	o.NextCursor = &v
}

func (o V1SuppressionsGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1SuppressionsGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.NextCursor) {
		toSerialize["next_cursor"] = o.NextCursor
	}
	return toSerialize, nil
}

type NullableV1SuppressionsGet200Response struct {
	value *V1SuppressionsGet200Response
	isSet bool
}

func (v NullableV1SuppressionsGet200Response) Get() *V1SuppressionsGet200Response {
	return v.value
}

func (v *NullableV1SuppressionsGet200Response) Set(val *V1SuppressionsGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1SuppressionsGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1SuppressionsGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1SuppressionsGet200Response(val *V1SuppressionsGet200Response) *NullableV1SuppressionsGet200Response {
	return &NullableV1SuppressionsGet200Response{value: val, isSet: true}
}

func (v NullableV1SuppressionsGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1SuppressionsGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


