/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"time"
)

// checks if the GetUserInsights200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUserInsights200Response{}

// GetUserInsights200Response struct for GetUserInsights200Response
type GetUserInsights200Response struct {
	RecentlyAdded []UserEvent `json:"recently_added,omitempty"`
	RecentlySuspended []UserEvent `json:"recently_suspended,omitempty"`
	Inactive30d []UserEvent `json:"inactive_30d,omitempty"`
	SeatsUsed *int32 `json:"seats_used,omitempty"`
	SeatsAlloc *int32 `json:"seats_alloc,omitempty"`
	// True only on tiers with a hard seat cap (Free, Founder). On unlimited/per-seat tiers seats_alloc merely tracks the live mailbox count, so seats_used == seats_alloc is normal and must not be read as 'at capacity'.
	SeatsCapped *bool `json:"seats_capped,omitempty"`
	GeneratedAt *time.Time `json:"generated_at,omitempty"`
}

// NewGetUserInsights200Response instantiates a new GetUserInsights200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserInsights200Response() *GetUserInsights200Response {
	this := GetUserInsights200Response{}
	return &this
}

// NewGetUserInsights200ResponseWithDefaults instantiates a new GetUserInsights200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserInsights200ResponseWithDefaults() *GetUserInsights200Response {
	this := GetUserInsights200Response{}
	return &this
}

// GetRecentlyAdded returns the RecentlyAdded field value if set, zero value otherwise.
func (o *GetUserInsights200Response) GetRecentlyAdded() []UserEvent {
	if o == nil || IsNil(o.RecentlyAdded) {
		var ret []UserEvent
		return ret
	}
	return o.RecentlyAdded
}

// GetRecentlyAddedOk returns a tuple with the RecentlyAdded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserInsights200Response) GetRecentlyAddedOk() ([]UserEvent, bool) {
	if o == nil || IsNil(o.RecentlyAdded) {
		return nil, false
	}
	return o.RecentlyAdded, true
}

// HasRecentlyAdded returns a boolean if a field has been set.
func (o *GetUserInsights200Response) HasRecentlyAdded() bool {
	if o != nil && !IsNil(o.RecentlyAdded) {
		return true
	}

	return false
}

// SetRecentlyAdded gets a reference to the given []UserEvent and assigns it to the RecentlyAdded field.
func (o *GetUserInsights200Response) SetRecentlyAdded(v []UserEvent) {
	o.RecentlyAdded = v
}

// GetRecentlySuspended returns the RecentlySuspended field value if set, zero value otherwise.
func (o *GetUserInsights200Response) GetRecentlySuspended() []UserEvent {
	if o == nil || IsNil(o.RecentlySuspended) {
		var ret []UserEvent
		return ret
	}
	return o.RecentlySuspended
}

// GetRecentlySuspendedOk returns a tuple with the RecentlySuspended field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserInsights200Response) GetRecentlySuspendedOk() ([]UserEvent, bool) {
	if o == nil || IsNil(o.RecentlySuspended) {
		return nil, false
	}
	return o.RecentlySuspended, true
}

// HasRecentlySuspended returns a boolean if a field has been set.
func (o *GetUserInsights200Response) HasRecentlySuspended() bool {
	if o != nil && !IsNil(o.RecentlySuspended) {
		return true
	}

	return false
}

// SetRecentlySuspended gets a reference to the given []UserEvent and assigns it to the RecentlySuspended field.
func (o *GetUserInsights200Response) SetRecentlySuspended(v []UserEvent) {
	o.RecentlySuspended = v
}

// GetInactive30d returns the Inactive30d field value if set, zero value otherwise.
func (o *GetUserInsights200Response) GetInactive30d() []UserEvent {
	if o == nil || IsNil(o.Inactive30d) {
		var ret []UserEvent
		return ret
	}
	return o.Inactive30d
}

// GetInactive30dOk returns a tuple with the Inactive30d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserInsights200Response) GetInactive30dOk() ([]UserEvent, bool) {
	if o == nil || IsNil(o.Inactive30d) {
		return nil, false
	}
	return o.Inactive30d, true
}

// HasInactive30d returns a boolean if a field has been set.
func (o *GetUserInsights200Response) HasInactive30d() bool {
	if o != nil && !IsNil(o.Inactive30d) {
		return true
	}

	return false
}

// SetInactive30d gets a reference to the given []UserEvent and assigns it to the Inactive30d field.
func (o *GetUserInsights200Response) SetInactive30d(v []UserEvent) {
	o.Inactive30d = v
}

// GetSeatsUsed returns the SeatsUsed field value if set, zero value otherwise.
func (o *GetUserInsights200Response) GetSeatsUsed() int32 {
	if o == nil || IsNil(o.SeatsUsed) {
		var ret int32
		return ret
	}
	return *o.SeatsUsed
}

// GetSeatsUsedOk returns a tuple with the SeatsUsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserInsights200Response) GetSeatsUsedOk() (*int32, bool) {
	if o == nil || IsNil(o.SeatsUsed) {
		return nil, false
	}
	return o.SeatsUsed, true
}

// HasSeatsUsed returns a boolean if a field has been set.
func (o *GetUserInsights200Response) HasSeatsUsed() bool {
	if o != nil && !IsNil(o.SeatsUsed) {
		return true
	}

	return false
}

// SetSeatsUsed gets a reference to the given int32 and assigns it to the SeatsUsed field.
func (o *GetUserInsights200Response) SetSeatsUsed(v int32) {
	o.SeatsUsed = &v
}

// GetSeatsAlloc returns the SeatsAlloc field value if set, zero value otherwise.
func (o *GetUserInsights200Response) GetSeatsAlloc() int32 {
	if o == nil || IsNil(o.SeatsAlloc) {
		var ret int32
		return ret
	}
	return *o.SeatsAlloc
}

// GetSeatsAllocOk returns a tuple with the SeatsAlloc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserInsights200Response) GetSeatsAllocOk() (*int32, bool) {
	if o == nil || IsNil(o.SeatsAlloc) {
		return nil, false
	}
	return o.SeatsAlloc, true
}

// HasSeatsAlloc returns a boolean if a field has been set.
func (o *GetUserInsights200Response) HasSeatsAlloc() bool {
	if o != nil && !IsNil(o.SeatsAlloc) {
		return true
	}

	return false
}

// SetSeatsAlloc gets a reference to the given int32 and assigns it to the SeatsAlloc field.
func (o *GetUserInsights200Response) SetSeatsAlloc(v int32) {
	o.SeatsAlloc = &v
}

// GetSeatsCapped returns the SeatsCapped field value if set, zero value otherwise.
func (o *GetUserInsights200Response) GetSeatsCapped() bool {
	if o == nil || IsNil(o.SeatsCapped) {
		var ret bool
		return ret
	}
	return *o.SeatsCapped
}

// GetSeatsCappedOk returns a tuple with the SeatsCapped field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserInsights200Response) GetSeatsCappedOk() (*bool, bool) {
	if o == nil || IsNil(o.SeatsCapped) {
		return nil, false
	}
	return o.SeatsCapped, true
}

// HasSeatsCapped returns a boolean if a field has been set.
func (o *GetUserInsights200Response) HasSeatsCapped() bool {
	if o != nil && !IsNil(o.SeatsCapped) {
		return true
	}

	return false
}

// SetSeatsCapped gets a reference to the given bool and assigns it to the SeatsCapped field.
func (o *GetUserInsights200Response) SetSeatsCapped(v bool) {
	o.SeatsCapped = &v
}

// GetGeneratedAt returns the GeneratedAt field value if set, zero value otherwise.
func (o *GetUserInsights200Response) GetGeneratedAt() time.Time {
	if o == nil || IsNil(o.GeneratedAt) {
		var ret time.Time
		return ret
	}
	return *o.GeneratedAt
}

// GetGeneratedAtOk returns a tuple with the GeneratedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserInsights200Response) GetGeneratedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.GeneratedAt) {
		return nil, false
	}
	return o.GeneratedAt, true
}

// HasGeneratedAt returns a boolean if a field has been set.
func (o *GetUserInsights200Response) HasGeneratedAt() bool {
	if o != nil && !IsNil(o.GeneratedAt) {
		return true
	}

	return false
}

// SetGeneratedAt gets a reference to the given time.Time and assigns it to the GeneratedAt field.
func (o *GetUserInsights200Response) SetGeneratedAt(v time.Time) {
	o.GeneratedAt = &v
}

func (o GetUserInsights200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUserInsights200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RecentlyAdded) {
		toSerialize["recently_added"] = o.RecentlyAdded
	}
	if !IsNil(o.RecentlySuspended) {
		toSerialize["recently_suspended"] = o.RecentlySuspended
	}
	if !IsNil(o.Inactive30d) {
		toSerialize["inactive_30d"] = o.Inactive30d
	}
	if !IsNil(o.SeatsUsed) {
		toSerialize["seats_used"] = o.SeatsUsed
	}
	if !IsNil(o.SeatsAlloc) {
		toSerialize["seats_alloc"] = o.SeatsAlloc
	}
	if !IsNil(o.SeatsCapped) {
		toSerialize["seats_capped"] = o.SeatsCapped
	}
	if !IsNil(o.GeneratedAt) {
		toSerialize["generated_at"] = o.GeneratedAt
	}
	return toSerialize, nil
}

type NullableGetUserInsights200Response struct {
	value *GetUserInsights200Response
	isSet bool
}

func (v NullableGetUserInsights200Response) Get() *GetUserInsights200Response {
	return v.value
}

func (v *NullableGetUserInsights200Response) Set(val *GetUserInsights200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserInsights200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserInsights200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserInsights200Response(val *GetUserInsights200Response) *NullableGetUserInsights200Response {
	return &NullableGetUserInsights200Response{value: val, isSet: true}
}

func (v NullableGetUserInsights200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserInsights200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


