/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Alias type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Alias{}

// Alias struct for Alias
type Alias struct {
	Id string `json:"id"`
	TenantId string `json:"tenant_id"`
	AliasAddress string `json:"alias_address"`
	AliasTarget string `json:"alias_target"`
	CreatedAt time.Time `json:"created_at"`
}

type _Alias Alias

// NewAlias instantiates a new Alias object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlias(id string, tenantId string, aliasAddress string, aliasTarget string, createdAt time.Time) *Alias {
	this := Alias{}
	this.Id = id
	this.TenantId = tenantId
	this.AliasAddress = aliasAddress
	this.AliasTarget = aliasTarget
	this.CreatedAt = createdAt
	return &this
}

// NewAliasWithDefaults instantiates a new Alias object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAliasWithDefaults() *Alias {
	this := Alias{}
	return &this
}

// GetId returns the Id field value
func (o *Alias) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Alias) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Alias) SetId(v string) {
	o.Id = v
}

// GetTenantId returns the TenantId field value
func (o *Alias) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *Alias) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *Alias) SetTenantId(v string) {
	o.TenantId = v
}

// GetAliasAddress returns the AliasAddress field value
func (o *Alias) GetAliasAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AliasAddress
}

// GetAliasAddressOk returns a tuple with the AliasAddress field value
// and a boolean to check if the value has been set.
func (o *Alias) GetAliasAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AliasAddress, true
}

// SetAliasAddress sets field value
func (o *Alias) SetAliasAddress(v string) {
	o.AliasAddress = v
}

// GetAliasTarget returns the AliasTarget field value
func (o *Alias) GetAliasTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AliasTarget
}

// GetAliasTargetOk returns a tuple with the AliasTarget field value
// and a boolean to check if the value has been set.
func (o *Alias) GetAliasTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AliasTarget, true
}

// SetAliasTarget sets field value
func (o *Alias) SetAliasTarget(v string) {
	o.AliasTarget = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Alias) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Alias) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Alias) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o Alias) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Alias) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["alias_address"] = o.AliasAddress
	toSerialize["alias_target"] = o.AliasTarget
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *Alias) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"tenant_id",
		"alias_address",
		"alias_target",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlias := _Alias{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAlias)

	if err != nil {
		return err
	}

	*o = Alias(varAlias)

	return err
}

type NullableAlias struct {
	value *Alias
	isSet bool
}

func (v NullableAlias) Get() *Alias {
	return v.value
}

func (v *NullableAlias) Set(val *Alias) {
	v.value = val
	v.isSet = true
}

func (v NullableAlias) IsSet() bool {
	return v.isSet
}

func (v *NullableAlias) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlias(val *Alias) *NullableAlias {
	return &NullableAlias{value: val, isSet: true}
}

func (v NullableAlias) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlias) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


