/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateDistributionListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateDistributionListRequest{}

// CreateDistributionListRequest struct for CreateDistributionListRequest
type CreateDistributionListRequest struct {
	ListAddress string `json:"list_address"`
	Name *string `json:"name,omitempty"`
	Members []string `json:"members,omitempty"`
}

type _CreateDistributionListRequest CreateDistributionListRequest

// NewCreateDistributionListRequest instantiates a new CreateDistributionListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateDistributionListRequest(listAddress string) *CreateDistributionListRequest {
	this := CreateDistributionListRequest{}
	this.ListAddress = listAddress
	return &this
}

// NewCreateDistributionListRequestWithDefaults instantiates a new CreateDistributionListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateDistributionListRequestWithDefaults() *CreateDistributionListRequest {
	this := CreateDistributionListRequest{}
	return &this
}

// GetListAddress returns the ListAddress field value
func (o *CreateDistributionListRequest) GetListAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ListAddress
}

// GetListAddressOk returns a tuple with the ListAddress field value
// and a boolean to check if the value has been set.
func (o *CreateDistributionListRequest) GetListAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ListAddress, true
}

// SetListAddress sets field value
func (o *CreateDistributionListRequest) SetListAddress(v string) {
	o.ListAddress = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateDistributionListRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDistributionListRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateDistributionListRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateDistributionListRequest) SetName(v string) {
	o.Name = &v
}

// GetMembers returns the Members field value if set, zero value otherwise.
func (o *CreateDistributionListRequest) GetMembers() []string {
	if o == nil || IsNil(o.Members) {
		var ret []string
		return ret
	}
	return o.Members
}

// GetMembersOk returns a tuple with the Members field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateDistributionListRequest) GetMembersOk() ([]string, bool) {
	if o == nil || IsNil(o.Members) {
		return nil, false
	}
	return o.Members, true
}

// HasMembers returns a boolean if a field has been set.
func (o *CreateDistributionListRequest) HasMembers() bool {
	if o != nil && !IsNil(o.Members) {
		return true
	}

	return false
}

// SetMembers gets a reference to the given []string and assigns it to the Members field.
func (o *CreateDistributionListRequest) SetMembers(v []string) {
	o.Members = v
}

func (o CreateDistributionListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateDistributionListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["list_address"] = o.ListAddress
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Members) {
		toSerialize["members"] = o.Members
	}
	return toSerialize, nil
}

func (o *CreateDistributionListRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"list_address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateDistributionListRequest := _CreateDistributionListRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateDistributionListRequest)

	if err != nil {
		return err
	}

	*o = CreateDistributionListRequest(varCreateDistributionListRequest)

	return err
}

type NullableCreateDistributionListRequest struct {
	value *CreateDistributionListRequest
	isSet bool
}

func (v NullableCreateDistributionListRequest) Get() *CreateDistributionListRequest {
	return v.value
}

func (v *NullableCreateDistributionListRequest) Set(val *CreateDistributionListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateDistributionListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateDistributionListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateDistributionListRequest(val *CreateDistributionListRequest) *NullableCreateDistributionListRequest {
	return &NullableCreateDistributionListRequest{value: val, isSet: true}
}

func (v NullableCreateDistributionListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateDistributionListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


