/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the Webhook type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Webhook{}

// Webhook struct for Webhook
type Webhook struct {
	Id string `json:"id"`
	TenantId string `json:"tenant_id"`
	Url string `json:"url"`
	Events []string `json:"events"`
	Paused bool `json:"paused"`
	PausedAt *time.Time `json:"paused_at,omitempty"`
	LastSuccessAt *time.Time `json:"last_success_at,omitempty"`
	LastFailureAt *time.Time `json:"last_failure_at,omitempty"`
	ConsecutiveFailures int32 `json:"consecutive_failures"`
	CreatedAt time.Time `json:"created_at"`
	// Hex-encoded HMAC-SHA256 key. Present ONLY on POST response.
	SigningSecret *string `json:"signing_secret,omitempty"`
}

type _Webhook Webhook

// NewWebhook instantiates a new Webhook object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhook(id string, tenantId string, url string, events []string, paused bool, consecutiveFailures int32, createdAt time.Time) *Webhook {
	this := Webhook{}
	this.Id = id
	this.TenantId = tenantId
	this.Url = url
	this.Events = events
	this.Paused = paused
	this.ConsecutiveFailures = consecutiveFailures
	this.CreatedAt = createdAt
	return &this
}

// NewWebhookWithDefaults instantiates a new Webhook object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookWithDefaults() *Webhook {
	this := Webhook{}
	return &this
}

// GetId returns the Id field value
func (o *Webhook) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *Webhook) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *Webhook) SetId(v string) {
	o.Id = v
}

// GetTenantId returns the TenantId field value
func (o *Webhook) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *Webhook) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *Webhook) SetTenantId(v string) {
	o.TenantId = v
}

// GetUrl returns the Url field value
func (o *Webhook) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *Webhook) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *Webhook) SetUrl(v string) {
	o.Url = v
}

// GetEvents returns the Events field value
func (o *Webhook) GetEvents() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Events
}

// GetEventsOk returns a tuple with the Events field value
// and a boolean to check if the value has been set.
func (o *Webhook) GetEventsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Events, true
}

// SetEvents sets field value
func (o *Webhook) SetEvents(v []string) {
	o.Events = v
}

// GetPaused returns the Paused field value
func (o *Webhook) GetPaused() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Paused
}

// GetPausedOk returns a tuple with the Paused field value
// and a boolean to check if the value has been set.
func (o *Webhook) GetPausedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Paused, true
}

// SetPaused sets field value
func (o *Webhook) SetPaused(v bool) {
	o.Paused = v
}

// GetPausedAt returns the PausedAt field value if set, zero value otherwise.
func (o *Webhook) GetPausedAt() time.Time {
	if o == nil || IsNil(o.PausedAt) {
		var ret time.Time
		return ret
	}
	return *o.PausedAt
}

// GetPausedAtOk returns a tuple with the PausedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Webhook) GetPausedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PausedAt) {
		return nil, false
	}
	return o.PausedAt, true
}

// HasPausedAt returns a boolean if a field has been set.
func (o *Webhook) HasPausedAt() bool {
	if o != nil && !IsNil(o.PausedAt) {
		return true
	}

	return false
}

// SetPausedAt gets a reference to the given time.Time and assigns it to the PausedAt field.
func (o *Webhook) SetPausedAt(v time.Time) {
	o.PausedAt = &v
}

// GetLastSuccessAt returns the LastSuccessAt field value if set, zero value otherwise.
func (o *Webhook) GetLastSuccessAt() time.Time {
	if o == nil || IsNil(o.LastSuccessAt) {
		var ret time.Time
		return ret
	}
	return *o.LastSuccessAt
}

// GetLastSuccessAtOk returns a tuple with the LastSuccessAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Webhook) GetLastSuccessAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastSuccessAt) {
		return nil, false
	}
	return o.LastSuccessAt, true
}

// HasLastSuccessAt returns a boolean if a field has been set.
func (o *Webhook) HasLastSuccessAt() bool {
	if o != nil && !IsNil(o.LastSuccessAt) {
		return true
	}

	return false
}

// SetLastSuccessAt gets a reference to the given time.Time and assigns it to the LastSuccessAt field.
func (o *Webhook) SetLastSuccessAt(v time.Time) {
	o.LastSuccessAt = &v
}

// GetLastFailureAt returns the LastFailureAt field value if set, zero value otherwise.
func (o *Webhook) GetLastFailureAt() time.Time {
	if o == nil || IsNil(o.LastFailureAt) {
		var ret time.Time
		return ret
	}
	return *o.LastFailureAt
}

// GetLastFailureAtOk returns a tuple with the LastFailureAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Webhook) GetLastFailureAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.LastFailureAt) {
		return nil, false
	}
	return o.LastFailureAt, true
}

// HasLastFailureAt returns a boolean if a field has been set.
func (o *Webhook) HasLastFailureAt() bool {
	if o != nil && !IsNil(o.LastFailureAt) {
		return true
	}

	return false
}

// SetLastFailureAt gets a reference to the given time.Time and assigns it to the LastFailureAt field.
func (o *Webhook) SetLastFailureAt(v time.Time) {
	o.LastFailureAt = &v
}

// GetConsecutiveFailures returns the ConsecutiveFailures field value
func (o *Webhook) GetConsecutiveFailures() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ConsecutiveFailures
}

// GetConsecutiveFailuresOk returns a tuple with the ConsecutiveFailures field value
// and a boolean to check if the value has been set.
func (o *Webhook) GetConsecutiveFailuresOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConsecutiveFailures, true
}

// SetConsecutiveFailures sets field value
func (o *Webhook) SetConsecutiveFailures(v int32) {
	o.ConsecutiveFailures = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *Webhook) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *Webhook) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *Webhook) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetSigningSecret returns the SigningSecret field value if set, zero value otherwise.
func (o *Webhook) GetSigningSecret() string {
	if o == nil || IsNil(o.SigningSecret) {
		var ret string
		return ret
	}
	return *o.SigningSecret
}

// GetSigningSecretOk returns a tuple with the SigningSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Webhook) GetSigningSecretOk() (*string, bool) {
	if o == nil || IsNil(o.SigningSecret) {
		return nil, false
	}
	return o.SigningSecret, true
}

// HasSigningSecret returns a boolean if a field has been set.
func (o *Webhook) HasSigningSecret() bool {
	if o != nil && !IsNil(o.SigningSecret) {
		return true
	}

	return false
}

// SetSigningSecret gets a reference to the given string and assigns it to the SigningSecret field.
func (o *Webhook) SetSigningSecret(v string) {
	o.SigningSecret = &v
}

func (o Webhook) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Webhook) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["tenant_id"] = o.TenantId
	toSerialize["url"] = o.Url
	toSerialize["events"] = o.Events
	toSerialize["paused"] = o.Paused
	if !IsNil(o.PausedAt) {
		toSerialize["paused_at"] = o.PausedAt
	}
	if !IsNil(o.LastSuccessAt) {
		toSerialize["last_success_at"] = o.LastSuccessAt
	}
	if !IsNil(o.LastFailureAt) {
		toSerialize["last_failure_at"] = o.LastFailureAt
	}
	toSerialize["consecutive_failures"] = o.ConsecutiveFailures
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.SigningSecret) {
		toSerialize["signing_secret"] = o.SigningSecret
	}
	return toSerialize, nil
}

func (o *Webhook) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"tenant_id",
		"url",
		"events",
		"paused",
		"consecutive_failures",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhook := _Webhook{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhook)

	if err != nil {
		return err
	}

	*o = Webhook(varWebhook)

	return err
}

type NullableWebhook struct {
	value *Webhook
	isSet bool
}

func (v NullableWebhook) Get() *Webhook {
	return v.value
}

func (v *NullableWebhook) Set(val *Webhook) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhook) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhook) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhook(val *Webhook) *NullableWebhook {
	return &NullableWebhook{value: val, isSet: true}
}

func (v NullableWebhook) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhook) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


