/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
)

// checks if the UpdateDirectoryPermissionsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDirectoryPermissionsRequest{}

// UpdateDirectoryPermissionsRequest struct for UpdateDirectoryPermissionsRequest
type UpdateDirectoryPermissionsRequest struct {
	ContactViewAccess *string `json:"contact_view_access,omitempty"`
	ContactEditAccess *string `json:"contact_edit_access,omitempty"`
	ListManageAccess *string `json:"list_manage_access,omitempty"`
	ExternalSharing *string `json:"external_sharing,omitempty"`
}

// NewUpdateDirectoryPermissionsRequest instantiates a new UpdateDirectoryPermissionsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDirectoryPermissionsRequest() *UpdateDirectoryPermissionsRequest {
	this := UpdateDirectoryPermissionsRequest{}
	return &this
}

// NewUpdateDirectoryPermissionsRequestWithDefaults instantiates a new UpdateDirectoryPermissionsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDirectoryPermissionsRequestWithDefaults() *UpdateDirectoryPermissionsRequest {
	this := UpdateDirectoryPermissionsRequest{}
	return &this
}

// GetContactViewAccess returns the ContactViewAccess field value if set, zero value otherwise.
func (o *UpdateDirectoryPermissionsRequest) GetContactViewAccess() string {
	if o == nil || IsNil(o.ContactViewAccess) {
		var ret string
		return ret
	}
	return *o.ContactViewAccess
}

// GetContactViewAccessOk returns a tuple with the ContactViewAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDirectoryPermissionsRequest) GetContactViewAccessOk() (*string, bool) {
	if o == nil || IsNil(o.ContactViewAccess) {
		return nil, false
	}
	return o.ContactViewAccess, true
}

// HasContactViewAccess returns a boolean if a field has been set.
func (o *UpdateDirectoryPermissionsRequest) HasContactViewAccess() bool {
	if o != nil && !IsNil(o.ContactViewAccess) {
		return true
	}

	return false
}

// SetContactViewAccess gets a reference to the given string and assigns it to the ContactViewAccess field.
func (o *UpdateDirectoryPermissionsRequest) SetContactViewAccess(v string) {
	o.ContactViewAccess = &v
}

// GetContactEditAccess returns the ContactEditAccess field value if set, zero value otherwise.
func (o *UpdateDirectoryPermissionsRequest) GetContactEditAccess() string {
	if o == nil || IsNil(o.ContactEditAccess) {
		var ret string
		return ret
	}
	return *o.ContactEditAccess
}

// GetContactEditAccessOk returns a tuple with the ContactEditAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDirectoryPermissionsRequest) GetContactEditAccessOk() (*string, bool) {
	if o == nil || IsNil(o.ContactEditAccess) {
		return nil, false
	}
	return o.ContactEditAccess, true
}

// HasContactEditAccess returns a boolean if a field has been set.
func (o *UpdateDirectoryPermissionsRequest) HasContactEditAccess() bool {
	if o != nil && !IsNil(o.ContactEditAccess) {
		return true
	}

	return false
}

// SetContactEditAccess gets a reference to the given string and assigns it to the ContactEditAccess field.
func (o *UpdateDirectoryPermissionsRequest) SetContactEditAccess(v string) {
	o.ContactEditAccess = &v
}

// GetListManageAccess returns the ListManageAccess field value if set, zero value otherwise.
func (o *UpdateDirectoryPermissionsRequest) GetListManageAccess() string {
	if o == nil || IsNil(o.ListManageAccess) {
		var ret string
		return ret
	}
	return *o.ListManageAccess
}

// GetListManageAccessOk returns a tuple with the ListManageAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDirectoryPermissionsRequest) GetListManageAccessOk() (*string, bool) {
	if o == nil || IsNil(o.ListManageAccess) {
		return nil, false
	}
	return o.ListManageAccess, true
}

// HasListManageAccess returns a boolean if a field has been set.
func (o *UpdateDirectoryPermissionsRequest) HasListManageAccess() bool {
	if o != nil && !IsNil(o.ListManageAccess) {
		return true
	}

	return false
}

// SetListManageAccess gets a reference to the given string and assigns it to the ListManageAccess field.
func (o *UpdateDirectoryPermissionsRequest) SetListManageAccess(v string) {
	o.ListManageAccess = &v
}

// GetExternalSharing returns the ExternalSharing field value if set, zero value otherwise.
func (o *UpdateDirectoryPermissionsRequest) GetExternalSharing() string {
	if o == nil || IsNil(o.ExternalSharing) {
		var ret string
		return ret
	}
	return *o.ExternalSharing
}

// GetExternalSharingOk returns a tuple with the ExternalSharing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDirectoryPermissionsRequest) GetExternalSharingOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalSharing) {
		return nil, false
	}
	return o.ExternalSharing, true
}

// HasExternalSharing returns a boolean if a field has been set.
func (o *UpdateDirectoryPermissionsRequest) HasExternalSharing() bool {
	if o != nil && !IsNil(o.ExternalSharing) {
		return true
	}

	return false
}

// SetExternalSharing gets a reference to the given string and assigns it to the ExternalSharing field.
func (o *UpdateDirectoryPermissionsRequest) SetExternalSharing(v string) {
	o.ExternalSharing = &v
}

func (o UpdateDirectoryPermissionsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDirectoryPermissionsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ContactViewAccess) {
		toSerialize["contact_view_access"] = o.ContactViewAccess
	}
	if !IsNil(o.ContactEditAccess) {
		toSerialize["contact_edit_access"] = o.ContactEditAccess
	}
	if !IsNil(o.ListManageAccess) {
		toSerialize["list_manage_access"] = o.ListManageAccess
	}
	if !IsNil(o.ExternalSharing) {
		toSerialize["external_sharing"] = o.ExternalSharing
	}
	return toSerialize, nil
}

type NullableUpdateDirectoryPermissionsRequest struct {
	value *UpdateDirectoryPermissionsRequest
	isSet bool
}

func (v NullableUpdateDirectoryPermissionsRequest) Get() *UpdateDirectoryPermissionsRequest {
	return v.value
}

func (v *NullableUpdateDirectoryPermissionsRequest) Set(val *UpdateDirectoryPermissionsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDirectoryPermissionsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDirectoryPermissionsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDirectoryPermissionsRequest(val *UpdateDirectoryPermissionsRequest) *NullableUpdateDirectoryPermissionsRequest {
	return &NullableUpdateDirectoryPermissionsRequest{value: val, isSet: true}
}

func (v NullableUpdateDirectoryPermissionsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDirectoryPermissionsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


