/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateEncryptionRecoveryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateEncryptionRecoveryRequest{}

// CreateEncryptionRecoveryRequest struct for CreateEncryptionRecoveryRequest
type CreateEncryptionRecoveryRequest struct {
	MailboxEmail string `json:"mailbox_email"`
	RecoveryBlob string `json:"recovery_blob"`
}

type _CreateEncryptionRecoveryRequest CreateEncryptionRecoveryRequest

// NewCreateEncryptionRecoveryRequest instantiates a new CreateEncryptionRecoveryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateEncryptionRecoveryRequest(mailboxEmail string, recoveryBlob string) *CreateEncryptionRecoveryRequest {
	this := CreateEncryptionRecoveryRequest{}
	this.MailboxEmail = mailboxEmail
	this.RecoveryBlob = recoveryBlob
	return &this
}

// NewCreateEncryptionRecoveryRequestWithDefaults instantiates a new CreateEncryptionRecoveryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateEncryptionRecoveryRequestWithDefaults() *CreateEncryptionRecoveryRequest {
	this := CreateEncryptionRecoveryRequest{}
	return &this
}

// GetMailboxEmail returns the MailboxEmail field value
func (o *CreateEncryptionRecoveryRequest) GetMailboxEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MailboxEmail
}

// GetMailboxEmailOk returns a tuple with the MailboxEmail field value
// and a boolean to check if the value has been set.
func (o *CreateEncryptionRecoveryRequest) GetMailboxEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MailboxEmail, true
}

// SetMailboxEmail sets field value
func (o *CreateEncryptionRecoveryRequest) SetMailboxEmail(v string) {
	o.MailboxEmail = v
}

// GetRecoveryBlob returns the RecoveryBlob field value
func (o *CreateEncryptionRecoveryRequest) GetRecoveryBlob() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecoveryBlob
}

// GetRecoveryBlobOk returns a tuple with the RecoveryBlob field value
// and a boolean to check if the value has been set.
func (o *CreateEncryptionRecoveryRequest) GetRecoveryBlobOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecoveryBlob, true
}

// SetRecoveryBlob sets field value
func (o *CreateEncryptionRecoveryRequest) SetRecoveryBlob(v string) {
	o.RecoveryBlob = v
}

func (o CreateEncryptionRecoveryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateEncryptionRecoveryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mailbox_email"] = o.MailboxEmail
	toSerialize["recovery_blob"] = o.RecoveryBlob
	return toSerialize, nil
}

func (o *CreateEncryptionRecoveryRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mailbox_email",
		"recovery_blob",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateEncryptionRecoveryRequest := _CreateEncryptionRecoveryRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateEncryptionRecoveryRequest)

	if err != nil {
		return err
	}

	*o = CreateEncryptionRecoveryRequest(varCreateEncryptionRecoveryRequest)

	return err
}

type NullableCreateEncryptionRecoveryRequest struct {
	value *CreateEncryptionRecoveryRequest
	isSet bool
}

func (v NullableCreateEncryptionRecoveryRequest) Get() *CreateEncryptionRecoveryRequest {
	return v.value
}

func (v *NullableCreateEncryptionRecoveryRequest) Set(val *CreateEncryptionRecoveryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateEncryptionRecoveryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateEncryptionRecoveryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateEncryptionRecoveryRequest(val *CreateEncryptionRecoveryRequest) *NullableCreateEncryptionRecoveryRequest {
	return &NullableCreateEncryptionRecoveryRequest{value: val, isSet: true}
}

func (v NullableCreateEncryptionRecoveryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateEncryptionRecoveryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


