/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DiscoverMigration202Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DiscoverMigration202Response{}

// DiscoverMigration202Response struct for DiscoverMigration202Response
type DiscoverMigration202Response struct {
	Status string `json:"status"`
}

type _DiscoverMigration202Response DiscoverMigration202Response

// NewDiscoverMigration202Response instantiates a new DiscoverMigration202Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDiscoverMigration202Response(status string) *DiscoverMigration202Response {
	this := DiscoverMigration202Response{}
	this.Status = status
	return &this
}

// NewDiscoverMigration202ResponseWithDefaults instantiates a new DiscoverMigration202Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDiscoverMigration202ResponseWithDefaults() *DiscoverMigration202Response {
	this := DiscoverMigration202Response{}
	return &this
}

// GetStatus returns the Status field value
func (o *DiscoverMigration202Response) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DiscoverMigration202Response) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DiscoverMigration202Response) SetStatus(v string) {
	o.Status = v
}

func (o DiscoverMigration202Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DiscoverMigration202Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *DiscoverMigration202Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDiscoverMigration202Response := _DiscoverMigration202Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDiscoverMigration202Response)

	if err != nil {
		return err
	}

	*o = DiscoverMigration202Response(varDiscoverMigration202Response)

	return err
}

type NullableDiscoverMigration202Response struct {
	value *DiscoverMigration202Response
	isSet bool
}

func (v NullableDiscoverMigration202Response) Get() *DiscoverMigration202Response {
	return v.value
}

func (v *NullableDiscoverMigration202Response) Set(val *DiscoverMigration202Response) {
	v.value = val
	v.isSet = true
}

func (v NullableDiscoverMigration202Response) IsSet() bool {
	return v.isSet
}

func (v *NullableDiscoverMigration202Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDiscoverMigration202Response(val *DiscoverMigration202Response) *NullableDiscoverMigration202Response {
	return &NullableDiscoverMigration202Response{value: val, isSet: true}
}

func (v NullableDiscoverMigration202Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDiscoverMigration202Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


