/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
)

// checks if the BatchLookupPublicKeys200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchLookupPublicKeys200Response{}

// BatchLookupPublicKeys200Response struct for BatchLookupPublicKeys200Response
type BatchLookupPublicKeys200Response struct {
	Data []BatchLookupPublicKeys200ResponseDataInner `json:"data,omitempty"`
}

// NewBatchLookupPublicKeys200Response instantiates a new BatchLookupPublicKeys200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchLookupPublicKeys200Response() *BatchLookupPublicKeys200Response {
	this := BatchLookupPublicKeys200Response{}
	return &this
}

// NewBatchLookupPublicKeys200ResponseWithDefaults instantiates a new BatchLookupPublicKeys200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchLookupPublicKeys200ResponseWithDefaults() *BatchLookupPublicKeys200Response {
	this := BatchLookupPublicKeys200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *BatchLookupPublicKeys200Response) GetData() []BatchLookupPublicKeys200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []BatchLookupPublicKeys200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchLookupPublicKeys200Response) GetDataOk() ([]BatchLookupPublicKeys200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *BatchLookupPublicKeys200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []BatchLookupPublicKeys200ResponseDataInner and assigns it to the Data field.
func (o *BatchLookupPublicKeys200Response) SetData(v []BatchLookupPublicKeys200ResponseDataInner) {
	o.Data = v
}

func (o BatchLookupPublicKeys200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchLookupPublicKeys200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableBatchLookupPublicKeys200Response struct {
	value *BatchLookupPublicKeys200Response
	isSet bool
}

func (v NullableBatchLookupPublicKeys200Response) Get() *BatchLookupPublicKeys200Response {
	return v.value
}

func (v *NullableBatchLookupPublicKeys200Response) Set(val *BatchLookupPublicKeys200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchLookupPublicKeys200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchLookupPublicKeys200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchLookupPublicKeys200Response(val *BatchLookupPublicKeys200Response) *NullableBatchLookupPublicKeys200Response {
	return &NullableBatchLookupPublicKeys200Response{value: val, isSet: true}
}

func (v NullableBatchLookupPublicKeys200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchLookupPublicKeys200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


