/*
lockally control plane

The lockally control plane lets integrators and direct customers manage everything except actual mail data flow (which uses standard JMAP / IMAP / SMTP-submission against the data plane endpoints).  **Authentication.** All `/v1/_*` endpoints require a Bearer API key in the `Authorization` header. Keys are formatted `lk_live_<8-char-prefix>_<32-char-secret>`. Generate the first key for a tenant via `cmd/seed`; subsequent keys via `POST /v1/api-keys`.  **Errors.** Failures return [RFC 9457](https://www.rfc-editor.org/rfc/rfc9457) `application/problem+json` documents.  **Scopes.** Each endpoint requires a specific scope on the presented key. Insufficient scope returns `403` with the required scope name in `detail`. 

API version: 0.1.0
Contact: support@lockally.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package lockally

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateContactRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateContactRequest{}

// CreateContactRequest struct for CreateContactRequest
type CreateContactRequest struct {
	Name string `json:"name"`
	Email string `json:"email"`
	Phone *string `json:"phone,omitempty"`
	Company *string `json:"company,omitempty"`
	Notes *string `json:"notes,omitempty"`
	ContactType *string `json:"contact_type,omitempty"`
	Department *string `json:"department,omitempty"`
	Role *string `json:"role,omitempty"`
}

type _CreateContactRequest CreateContactRequest

// NewCreateContactRequest instantiates a new CreateContactRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateContactRequest(name string, email string) *CreateContactRequest {
	this := CreateContactRequest{}
	this.Name = name
	this.Email = email
	var contactType string = "external"
	this.ContactType = &contactType
	return &this
}

// NewCreateContactRequestWithDefaults instantiates a new CreateContactRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateContactRequestWithDefaults() *CreateContactRequest {
	this := CreateContactRequest{}
	var contactType string = "external"
	this.ContactType = &contactType
	return &this
}

// GetName returns the Name field value
func (o *CreateContactRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateContactRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateContactRequest) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *CreateContactRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *CreateContactRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *CreateContactRequest) SetEmail(v string) {
	o.Email = v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *CreateContactRequest) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateContactRequest) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *CreateContactRequest) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *CreateContactRequest) SetPhone(v string) {
	o.Phone = &v
}

// GetCompany returns the Company field value if set, zero value otherwise.
func (o *CreateContactRequest) GetCompany() string {
	if o == nil || IsNil(o.Company) {
		var ret string
		return ret
	}
	return *o.Company
}

// GetCompanyOk returns a tuple with the Company field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateContactRequest) GetCompanyOk() (*string, bool) {
	if o == nil || IsNil(o.Company) {
		return nil, false
	}
	return o.Company, true
}

// HasCompany returns a boolean if a field has been set.
func (o *CreateContactRequest) HasCompany() bool {
	if o != nil && !IsNil(o.Company) {
		return true
	}

	return false
}

// SetCompany gets a reference to the given string and assigns it to the Company field.
func (o *CreateContactRequest) SetCompany(v string) {
	o.Company = &v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *CreateContactRequest) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateContactRequest) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *CreateContactRequest) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *CreateContactRequest) SetNotes(v string) {
	o.Notes = &v
}

// GetContactType returns the ContactType field value if set, zero value otherwise.
func (o *CreateContactRequest) GetContactType() string {
	if o == nil || IsNil(o.ContactType) {
		var ret string
		return ret
	}
	return *o.ContactType
}

// GetContactTypeOk returns a tuple with the ContactType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateContactRequest) GetContactTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContactType) {
		return nil, false
	}
	return o.ContactType, true
}

// HasContactType returns a boolean if a field has been set.
func (o *CreateContactRequest) HasContactType() bool {
	if o != nil && !IsNil(o.ContactType) {
		return true
	}

	return false
}

// SetContactType gets a reference to the given string and assigns it to the ContactType field.
func (o *CreateContactRequest) SetContactType(v string) {
	o.ContactType = &v
}

// GetDepartment returns the Department field value if set, zero value otherwise.
func (o *CreateContactRequest) GetDepartment() string {
	if o == nil || IsNil(o.Department) {
		var ret string
		return ret
	}
	return *o.Department
}

// GetDepartmentOk returns a tuple with the Department field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateContactRequest) GetDepartmentOk() (*string, bool) {
	if o == nil || IsNil(o.Department) {
		return nil, false
	}
	return o.Department, true
}

// HasDepartment returns a boolean if a field has been set.
func (o *CreateContactRequest) HasDepartment() bool {
	if o != nil && !IsNil(o.Department) {
		return true
	}

	return false
}

// SetDepartment gets a reference to the given string and assigns it to the Department field.
func (o *CreateContactRequest) SetDepartment(v string) {
	o.Department = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *CreateContactRequest) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateContactRequest) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *CreateContactRequest) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *CreateContactRequest) SetRole(v string) {
	o.Role = &v
}

func (o CreateContactRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateContactRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["email"] = o.Email
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	if !IsNil(o.Company) {
		toSerialize["company"] = o.Company
	}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.ContactType) {
		toSerialize["contact_type"] = o.ContactType
	}
	if !IsNil(o.Department) {
		toSerialize["department"] = o.Department
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

func (o *CreateContactRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateContactRequest := _CreateContactRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateContactRequest)

	if err != nil {
		return err
	}

	*o = CreateContactRequest(varCreateContactRequest)

	return err
}

type NullableCreateContactRequest struct {
	value *CreateContactRequest
	isSet bool
}

func (v NullableCreateContactRequest) Get() *CreateContactRequest {
	return v.value
}

func (v *NullableCreateContactRequest) Set(val *CreateContactRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateContactRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateContactRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateContactRequest(val *CreateContactRequest) *NullableCreateContactRequest {
	return &NullableCreateContactRequest{value: val, isSet: true}
}

func (v NullableCreateContactRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateContactRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


